#+Title: Configuration Files
#+CATEGORY: Configuration
#+DESCRIPTION: Herein contains my configuration files that configure my environment on different computer systems
#+PROPERTY:  header-args:emacs-lisp :tangle yes :mkdirp yes
#+STARTUP: overview


* Table of Contents                                                        :TOC_5:
- [[#description-and-usage][Description and Usage]]
- [[#contents-of-this-repository][Contents of this repository]]
  - [[#emacs-configurations][Emacs Configurations]]
  - [[#git-configurations][Git Configurations]]
  - [[#gpg-configuration][GPG Configuration]]
  - [[#shell-configuration][Shell Configuration]]
  - [[#vim-configuration][Vim Configuration]]
  - [[#other-configurations][Other Configurations]]
  - [[#nix-configurations][Nix Configurations]]

* Description and Usage
This repository holds all the configurations needed to run the different systems
I generally use on any given day. To use this then emacs should generate all the
necessary file using `org-babel` and create the necessary configuration
folders. There are files that may store sensitive information and configuration
such as keys needed to access servers, passwords/security tokens to Github or
other accounts. Hence, for security purposes these files gets encrypted using
[[https://www.gnupg.org/][The GNU Privacy Guard]] or [[https://github.com/AGWA/git-crypt][Git Crypt]] and are inaccessible, so they do not appear
listed here.

* Contents of this repository
** Emacs Configurations

Contains all my Emacs configurations.

** Git Configurations

 This is where I store my git personalisations.

** GPG Configuration

GPG configurations are stored here.

** Shell Configuration

What my shell environment looks like

** Vim Configuration

Contains simple Vim configurations.

** Other Configurations

This is where I store configurations that are not categorised.

** Nix Configurations

In this configuration declare how to setup my environment.
