#+Title: Emacs Configurations
#+CATEGORY: Configuration
#+PROPERTY:  header-args:emacs-lisp :tangle yes :mkdirp yes
#+STARTUP: overview


* Emacs Configuration
** Root Folder
*** Init File
  #+begin_src emacs-lisp :tangle ~/.emacs.d/lisp/init-local.el :mkdirp yes
    ;;; init-local.el --- Load the full configuration -*- lexical-binding: t -*-
    ;;; Commentary:

    ;; This file bootstraps the configuration, which is divided into
    ;; a number of other files.

    ;;; Code:

    ;; Produce backtraces when errors occur: can be helpful to diagnose startup issues
    (setq debug-on-error nil)

    (add-to-list 'load-path (expand-file-name "custom" user-emacs-directory))

    ;;----------------------------------------------------------------------------
    ;; Taken from https://github.com/akermu/emacs-libvterm/issues/18
    ;; Fixes this vterm-module problem:
    ;; apply: Cannot open load file: No such file or directory, vterm-module
    ;;----------------------------------------------------------------------------
    ;; (setq system-configuration-options "--with-ns '--enable-locallisppath=/Library/Application Support/Emacs/${version}/site-lisp:/Library/Application Support/Emacs/site-lisp' --with-modules 'CFLAGS=-DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT' --with-x-toolkit=no --with-modules")

    ;;----------------------------------------------------------------------------
    ;; Adjust garbage collection thresholds during startup, and thereafter
    ;;----------------------------------------------------------------------------
    (let ((normal-gc-cons-threshold (* 100 1024 1024))
          (init-gc-cons-threshold (* 2 256 1024 1024)))
      (setq gc-cons-threshold init-gc-cons-threshold
            read-process-output-max (* 1024 1024))
      (add-hook 'emacs-startup-hook
                (lambda () (setq gc-cons-threshold normal-gc-cons-threshold))))


    (require 'init-use-package)

    ;;----------------------------------------------------------------------------
    ;; Customizations
    ;;----------------------------------------------------------------------------
    ;; This module is supplied separately from encrypted secrets when available.
    (require 'init-ai nil t)
    (require 'init-evil)
    (require 'init-corfu-customizations)
    (require 'init-dart)
    (require 'init-defaults)
    (require 'init-dired-customizations)
    (require 'init-editing-utils-customizations)
    (require 'init-exec-path-customizations)
    (require 'init-general)
    (require 'init-graphql)
    (require 'init-helper-packages)
    (require 'init-helpful)
    (require 'init-hydra)
    (require 'init-dumb-jump)
    (require 'init-icons)
    (require 'init-magit)
    (require 'init-navigation)
    (require 'init-prisma)
    (require 'init-perspective)
    (require 'init-projectile-customizations)
    (require 'init-protobuf)
    (require 'init-master)
    (require 'init-restart-emacs)
    (require 'init-rust-customizations)
    (require 'init-security)
    (require 'init-shell)
    (require 'init-solidity)
    (require 'init-sql-customizations)
    (require 'init-treemacs)
    (require 'init-treesitter-customizations)
    (require 'init-webdev)
    (require 'init-golang)
    (require 'init-org-customizations)
    (require 'init-eglot-customizations)
    (require 'init-pdf)
    (require 'init-nix-customizations)
    (require 'init-minibuffer-customizations)
    (require 'init-merged-extras)
    ;; (require 'init-lsp)
    ;; (require 'init-tailwind)
    ;; (require 'init-plantuml)
    ;; (require 'init-tramp)

    (provide 'init-local)

    ;; Local Variables:
    ;; coding: utf-8
    ;; no-byte-compile: t
    ;; End:
    ;;; init.el ends here

  #+end_src

*** Lisp Folder
    Decrypt and remove the crypt directive or it won't tangle
**** AI                                                                         :crypt:
-----BEGIN PGP MESSAGE-----

hQIMA0W4l8nHGHn8ARAAjj1bAOupclYr3R/58C6NChaQ0kf9Tb6/cbJlp6vVyGhr
JxymCfANmOa0oK7LdQ95ZE12cMow/6wPLeOBgygSSPLgEIL0Ga8fqDcSqk/s4gOQ
wM4HxdDSdeGNVz3emri/FMBSEHFtUNDCeQAIQQcsnRLQY9a70ETnuAdkLH0Pbhh1
YkkbG1bFgVSFzcMg7ZWWLxj5rL3TgMv1BzHzGjflL/8x+LU46s4YEh7t5y2rgdTx
wOADK38F6OyK99o2liTy1wGwP0tFoTAYzsse1pITLVE5wAW1FCEYhIN5scC8ryIz
lB+e1Sc0jZvAFZ8cht8cYe9Vcq55ZbpoZoalpWFagdQRrgZdUA8Zklc9mfT+sdT9
DEXf+ocxvLm3XXpG9xzV4/tGtYKRp4zMzZWjyyZGChsN63a8Y3MxTfDQAYOWCZXU
LPnmZGl0wVxWnrygLtfqWnnikJ8cd5MzSJXNA8YLaxlQ8HxHmvEhNr0HFh2gPx/V
G0syw6zhggMY0lvq6tKyJpgANZvKCwRheLtbKiSJeKUPhLMnB0PNdEwk8+iYE/lL
5CZU2XN/ayI4Bn6O1R5TXQg0USTjHfj6VqH80vxObStw+HbMRribRTo75cRQTLWu
hz7XPpXoXgqGZuhihf3KON3Qw4nrT9gwu0svPcwmfpKkMQ+xWtp2KiMpfW4kctLS
wKcBKv/EnOe+37DeOwo1yVpHWnh+wbu16LtnMfwL4uFPJ+/voKJykNARBRCqTb+6
beROzj3N2ijpwxo+B0yxgzqJiHD+rN8d0uxhtQBxlcUoFSimIlgzGoLA1twE9yH1
0xDH0U2vgcjiYxew5PLBcp1D7F/6HveDupOebVQGADmboKudqDxeIP99IeVXIWOa
CSZwiveqqmXexWbc4tqUlg9E/4ilfuD0a7hyVsbEVnAO8Lp+g0uvAkcLsmIU/eBy
oEcGXCsYMxm+69J48o8JfBgxnC0+YJshtjORTNk8s+dUMHKdPy18hAAH/QQURb2O
0/i8uGHvAoNco0+kFv3GhcuXGc0gWJUbM0vcTHgImmqTC0MjkoV+j7Ki5HakRPI/
QyHA70tUPxR8hr/eUodiaJAfccTVt7b86b77Pn8tMu9caV7LUNlzXj8fxztCQ5EB
LXboy79tJWDCCKofHmbNTYuDjDhD5/QUcg==
=2+Yv
-----END PGP MESSAGE-----
**** Corfu
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-corfu-customizations.el :mkdirp yes
  ;;; init-corfu-customizations.el --- Completion with Corfu -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package corfu
    :ensure t
    :demand t
    :custom
    (corfu-auto t)
    (corfu-auto-delay 0.2)
    (corfu-auto-prefix 2)
    (corfu-cycle t)
    (corfu-quit-no-match 'separator)
    :config
    ;; The upstream configuration enables this from `after-init-hook'.  Make
    ;; the desired state explicit so reloading this module cannot toggle it.
    (remove-hook 'after-init-hook #'global-corfu-mode)
    (global-corfu-mode 1)
    (corfu-popupinfo-mode 1))

  (use-package svg-lib)
  (use-package kind-icon
    :ensure t
    :after corfu
    :custom
    (kind-icon-blend-background t)
    (kind-icon-default-face 'corfu-default) ; only needed with blend-background
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))

  (provide 'init-corfu-customizations)
  ;;; init-corfu-customizations.el ends here

#+end_src
**** Defaults
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-defaults.el :mkdirp yes
  ;;; init-defaults.el --- Support defaults -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;;----------------------------------------------------------------------------
  ;; Remap option key to super
  ;;----------------------------------------------------------------------------
  (when *is-a-mac*
    (setq mac-option-modifier 'super))

  ;;----------------------------------------------------------------------------
  ;; Setup some stuff for my frame
  ;;----------------------------------------------------------------------------
  (unless (package-installed-p 'fancy-battery)
    (package-install 'fancy-battery))

  (setq battery-update-interval 15)
  (setq fancy-battery-show-percentage t)
  (add-hook 'after-init-hook #'fancy-battery-mode)

  (setq display-time-day-and-date t)
  (display-time)

  ;;----------------------------------------------------------------------------
  ;; Frame title and dimension
  ;;----------------------------------------------------------------------------
  (setq rb/new-frame-title (concat " " user-login-name " is the best (•̀ᴗ•́)"))
  (setq frame-title-format '("%b --> " rb/new-frame-title))
  (setq load-prefer-newer t)
  (setq enable-local-variables :safe)
  ;; (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;;----------------------------------------------------------------------------
  ;; Taking of the cursor and lines
  ;;----------------------------------------------------------------------------
  (blink-cursor-mode 0)
  (global-hl-line-mode t)

  (dolist (mode '(prog-mode-hook
                  text-mode-hook
                  treemacs-mode-hook))
    (add-hook mode (lambda () (setq-local truncate-lines t))))

  ;;----------------------------------------------------------------------------
  ;; Save bookmarks automagically
  ;;----------------------------------------------------------------------------
  (setq bookmark-save-flag 1)

  ;;----------------------------------------------------------------------------
  ;; Copied from:
  ;; https://superuser.com/questions/77314/how-to-do-select-column-then-do-editing-in-gnu-emacs
  ;;----------------------------------------------------------------------------
  (setq cua-enable-cua-keys nil)
  (setq cua-highlight-region-shift-only t)
  (setq cua-toggle-set-mark nil)

  ;;----------------------------------------------------------------------------
  ;; change all prompts to y or n
  ;;----------------------------------------------------------------------------
  (fset 'yes-or-no-p 'y-or-n-p)


  (setq user-full-name    "Randy Burrell"
        user-mail-address "rb@randyburrell.info")
  ;;----------------------------------------------------------------------------
  ;; This sets confirm killing emacs
  ;;----------------------------------------------------------------------------
  ;; (setq confirm-kill-emacs 'yes-or-no-p)

  ;;----------------------------------------------------------------------------
  ;; Line width
  ;;----------------------------------------------------------------------------
  (setq-default fill-column 80
                indent-tabs-mode nil)

  ;;----------------------------------------------------------------------------
  ;; Let's just set the default shell
  ;;----------------------------------------------------------------------------
  (setq explicit-shell-file-name "/bin/zsh")

  ;;----------------------------------------------------------------------------
  ;; Delete trailing white-spaces
  ;;----------------------------------------------------------------------------
  (add-hook 'write-file-hooks 'delete-trailing-whitespace)

  ;;----------------------------------------------------------------------------
  ;; Use esc to exit mini-buffer
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  ;;----------------------------------------------------------------------------
  ;; Comment or uncomment region
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "C-x C-'") 'comment-or-uncomment-region)

  ;;----------------------------------------------------------------------------
  ;; Use esc to exit mini-buffer
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "C-M-<return>") 'scroll-other-window-down)

  ;;----------------------------------------------------------------------------
  (provide 'init-defaults)
  ;;; init-defaults.el ends here

#+end_src

**** Debugger
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-lsp.el :mkdirp yes
  ;;; init-debugger.el --- Provides completion engine -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; Debugging with tools like dape-mode
  ;;; Code:

  (use-package dape
    :preface
    ;; By default dape shares the same keybinding prefix as `gud'
    ;; If you do not want to use any prefix, set it to nil.
    ;; (setq dape-key-prefix "\C-x\C-a")
    (setq dape-key-prefix "M-\"")

    :hook
    ;; Save breakpoints on quit
    ((kill-emacs . dape-breakpoint-save)
     ;; Load breakpoints on startup
     (after-init . dape-breakpoint-load))

    :init
    ;; To use window configuration like gud (gdb-mi)
    ;; (setq dape-buffer-window-arrangement 'gud)

    :config
    ;; Info buffers to the right
    (setq dape-buffer-window-arrangement 'right)

    ;; Global bindings for setting breakpoints with mouse
    (dape-breakpoint-global-mode)

    ;; To not display info and/or buffers on startup
    ;; (remove-hook 'dape-on-start-hooks 'dape-info)
    ;; (remove-hook 'dape-on-start-hooks 'dape-repl)

    ;; To display info and/or repl buffers on stopped
    ;; (add-hook 'dape-on-stopped-hooks 'dape-info)
    ;; (add-hook 'dape-on-stopped-hooks 'dape-repl)

    ;; Kill compile buffer on build success
    ;; (add-hook 'dape-compile-compile-hooks 'kill-buffer)

    ;; Save buffers on startup, useful for interpreted languages
    ;; (add-hook 'dape-on-start-hooks (lambda () (save-some-buffers t t)))

    ;; Projectile users
    (setq dape-cwd-fn 'projectile-project-root))

  (add-to-list
   'dape-configs
   `(tsx-debug-node
     modes (tsx-ts-mode)
     command "node"
     command-args (,(expand-file-name "debug-adapters/extension/dist/debugAdapter.js" user-emacs-directory) :autoport)
     port :autoport
     :type "pwa-node"
     :runtimeExecutable "ts-node"
     :cwd dape-cwd
     :program dape-buffer-default
     :console "internalConsole"
     :port 3031
     ))


  (add-to-list
   'dape-configs
   `(tsx-debug-node-attach
     modes (tsx-ts-mode)
     command "node"
     command-args (,(expand-file-name "debug-adapters/extension/dist/debugAdapter.js" user-emacs-directory) :autoport)
     port :autoport
     :type "pwa-chrome"
     :url "http://localhost:3000"
     :web-root dape-cwd
     :cwd dape-cwd
     :program dape-buffer-default
     :console "internalConsole"
     :port 3031
     ))

  (provide 'init-dedugger)
  ;;; init-lsp.el ends here

#+end_src

**** Dired
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-dired-customizations.el :mkdirp yes
  ;;; init-dired-customizations.el --- Dired-customizations customisations -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (with-eval-after-load 'dired
    (put 'dired-find-alternate-file 'disabled nil)
    (define-key dired-mode-map "h" #'dired-up-directory)
    (define-key dired-mode-map "l" #'dired-find-alternate-file)
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" #'dired-up-directory
      "l" #'dired-find-alternate-file))

  (use-package dired-open)

  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (define-key dired-mode-map "H" 'dired-hide-dotfiles-mode)
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))

  ;; While we're at it: Make dired, ‘dir’ectory ‘ed’itor, look pretty
  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  (setq completion-ignored-extensions
        (append completion-ignored-extensions
                (quote
                 (".~undo-tree~"))))

  (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))

  ;; Show directories first
  (setq dired-listing-switches "-aBhl --group-directories-first")

  (when *is-a-mac*
    (setq dired-use-ls-dired t
          insert-directory-program "/opt/homebrew/opt/coreutils/libexec/gnubin/ls"))

  (provide 'init-dired-customizations)
  ;;; init-dired-customizations.el ends here

#+end_src

**** Dumb Jump
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-dumb-jump.el :mkdirp yes
  ;;; init-dumb-jump.el --- Dumb Jump Customizations -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package dumb-jump
    :config
    (setq dumb-jump-force-searcher 'rg))

  (defhydra dumb-jump-hydra (:color blue :columns 3)
    "Dumb Jump"
    ("j" dumb-jump-go "Go")
    ("o" dumb-jump-go-other-window "Other window")
    ("e" dumb-jump-go-prefer-external "Go external")
    ("x" dumb-jump-go-prefer-external-other-window "Go external other window")
    ("i" dumb-jump-go-prompt "Prompt")
    ("l" dumb-jump-quick-look "Quick look")
    ("b" dumb-jump-back "Back"))

  (provide 'init-dumb-jump)
  ;;; init-dumb-jump.el ends here

#+end_src

**** Editing Utilities
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-editing-utils-customizations.el :mkdirp yes
  ;;; init-editing-utils-customizations.el --- Day-to-day editing helpers -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (require-package 'unfill)

  (when (fboundp 'electric-pair-mode)
    (add-hook 'after-init-hook 'electric-pair-mode))
  (add-hook 'after-init-hook 'electric-indent-mode)

  (maybe-require-package 'list-unicode-display)


  ;;; Some basic preferences

  (setq-default
   bookmark-default-file (expand-file-name ".bookmarks.el" user-emacs-directory))

  ;;----------------------------------------------------------------------------
  ;; Set up line number
  ;;----------------------------------------------------------------------------
  (defun rb/display-line-numbers-mode ()
    "Setup line number for buffer."
    (setq display-line-numbers-width 1
          display-line-numbers-width-start t
          display-line-numbers-type 'relative)
    ;; (global-display-line-numbers-mode      nil)
    (display-line-numbers-mode))

  (when (fboundp 'display-line-numbers-mode)
    (add-hook 'prog-mode-hook 'rb/display-line-numbers-mode)
    (add-hook 'text-mode-hook 'rb/display-line-numbers-mode)
    (add-hook 'treemacs-mode-hook 'rb/display-line-numbers-mode))

  ;; Use one accessible face for automatic occurrences from both the local
  ;; symbol highlighter and Eglot's documentHighlight support.
  (custom-set-faces
   '(symbol-overlay-default-face
     ((t (:background "#1d4ed8" :foreground "#ffffff" :weight semi-bold))))
   '(eglot-highlight-symbol-face
     ((t (:background "#1d4ed8" :foreground "#ffffff" :weight semi-bold)))))

  (provide 'init-editing-utils-customizations)
  ;;; init-editing-utils-customizations.el ends here

#+end_src

**** Eglot
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-eglot-customizations.el :mkdirp yes
  ;;; init-eglot-customizations.el --- Eglot and completion setup -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; Start an installed language server automatically and expose its
  ;; completion-at-point backend through Corfu.
  ;;; Code:

  (with-eval-after-load 'eglot
    (add-to-list 'eglot-server-programs
                 '((web-mode :language-id "typescriptreact")
                   . ("typescript-language-server" "--stdio")))
    (add-to-list 'eglot-server-programs
                 `((nix-mode nix-ts-mode)
                   . ,(eglot-alternatives '("nil" "nixd"))))
    (add-to-list 'eglot-server-programs
                 '((rust-mode rust-ts-mode) . ("rust-analyzer"))))

  (defun rb/eglot-ensure ()
    "Start Eglot, reporting a missing or broken server without breaking MODE."
    (condition-case err
        (eglot-ensure)
      (error
       (message "Eglot could not start for %s: %s"
                major-mode (error-message-string err)))))

  (dolist (mode '(sh-mode-hook
                  bash-ts-mode-hook
                  c-mode-hook
                  c-ts-mode-hook
                  c++-mode-hook
                  c++-ts-mode-hook
                  css-mode-hook
                  css-ts-mode-hook
                  dockerfile-mode-hook
                  dockerfile-ts-mode-hook
                  go-mode-hook
                  go-ts-mode-hook
                  go-mod-ts-mode-hook
                  html-mode-hook
                  html-ts-mode-hook
                  web-mode-hook
                  js-mode-hook
                  js-ts-mode-hook
                  json-mode-hook
                  json-ts-mode-hook
                  nix-mode-hook
                  nix-ts-mode-hook
                  python-mode-hook
                  python-ts-mode-hook
                  rust-mode-hook
                  rust-ts-mode-hook
                  terraform-mode-hook
                  typescript-mode-hook
                  typescript-ts-mode-hook
                  tsx-ts-mode-hook
                  yaml-mode-hook
                  yaml-ts-mode-hook))
    (remove-hook mode #'eglot-ensure)
    (add-hook mode #'rb/eglot-ensure))

  (setq eglot-autoshutdown t
        eglot-sync-connect 3
        eglot-events-buffer-size 2000000)
  (add-hook 'focus-out-hook 'garbage-collect)

  (provide 'init-eglot-customizations)
  ;;; init-eglot-customizations.el ends here
#+end_src
**** Evil Mode
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-evil.el :mkdirp yes
  ;;; init-evil.el --- Provides evil -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; vim like bindings
  ;;; Code:

  (use-package evil
    :diminish
    :init
    (progn
      (setq evil-undo-system 'undo-tree
            evil-want-integration t
            evil-want-keybinding nil
            evil-want-C-u-scroll t
            evil-want-C-i-jump nil))
    :config
    (evil-mode nil)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)
    (define-key evil-insert-state-map (kbd "C-k") 'evil-previous-visual-line)
    (define-key evil-insert-state-map (kbd "C-j") 'evil-next-visual-line)
    (define-key evil-insert-state-map (kbd "C-e") 'evil-append-line)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal)
    (evil-set-leader '(normal visual) "\\" )
    (evil-define-key '(normal visual) 'global (kbd "<leader>s") 'save-buffer)
    (evil-define-key '(normal visual) 'global (kbd "<leader>`") 'split-window-right)
    (evil-define-key '(normal visual) 'global (kbd "<leader>;") 'split-window-below)
    (evil-define-key '(normal visual) 'global (kbd "<leader>x") 'kill-buffer-and-window)
    (evil-define-key '(normal visual) 'global (kbd "<leader>h") 'evil-window-increase-height)
    (evil-define-key '(normal visual) 'global (kbd "<leader>w") 'evil-window-increase-width)
    (evil-define-key '(normal visual) 'global (kbd "<leader>=") 'evil-window-decrease-height)
    (evil-define-key '(normal visual) 'global (kbd "<leader>-") 'evil-window-decrease-width)
    (evil-define-key '(normal visual) 'global (kbd "<leader>ew") 'balance-windows)
    (evil-define-key '(normal visual) 'global (kbd "<leader>b") 'switch-to-buffer)
    (evil-define-key '(normal visual) 'global (kbd "<leader>[") 'other-frame)
    (evil-define-key '(normal visual) 'global (kbd "<leader>f") 'make-frame)
    (evil-define-key '(normal visual) 'global (kbd "<leader>0") 'delete-frame)
    (evil-define-key '(normal visual) 'global (kbd "<leader>q")
      (lambda (&optional prefix)
        (interactive "P")
        (pcase (or (car prefix) 0)
          (0  (kill-this-buffer))
          (4  (other-window 1)
              (kill-this-buffer)
              (unless (one-window-p) (delete-window)))
          (16   (mapc 'kill-buffer (delq (current-buffer) (buffer-list)))
                (delete-other-windows)))))
    (use-package evil-surround
      :diminish
      :after evil
      :config
      (global-evil-surround-mode 1))
    (use-package evil-collection
      :diminish
      :after evil
      :config
      (setq forge-add-default-bindings nil
            evil-collection-setup-minibuffer t)
      (evil-collection-init))
    (use-package evil-nerd-commenter
      :diminish
      :after evil
      :bind ("s-\\" . evilnc-comment-or-uncomment-lines)))

  (provide 'init-evil)
  ;;; init-evil.el ends here

#+end_src

**** Find File In Project
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-find-file-in-project.el :mkdirp yes
  ;;; init-find-file-in-project.el --- loads treemacs package -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:
  (use-package find-file-in-project
      :config
      (remove-hook 'file-name-at-point-functions 'ffap-guess-file-name-at-point))
  ;;; init-find-file-in-project.el ends here

#+end_src

**** Flutter
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-dart.el :mkdirp yes
  ;;; init-dart.el --- Support Dart files -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package dart-mode
    ;; Optional
    :hook (dart-mode . flutter-test-mode))

  (use-package flutter
    :after dart-mode
    :bind (:map dart-mode-map
                ("C-M-x" . #'flutter-run-or-hot-reload))
    :custom
    (flutter-sdk-path "/opt/homebrew/bin/flutter"))

  (with-eval-after-load "eglot" (add-to-list 'eglot-server-programs '(dart-mode . ("dart" "language-server"))))

  (add-hook 'dart-mode-hook 'eglot-ensure)

  (reformatter-define dart-format
    :program "dart"
    :args '("format"))

  (with-eval-after-load "dart-mode"
    (define-key dart-mode-map (kbd "C-c C-o") 'dart-format-buffer))

  (add-hook 'dart-mode-hook (lambda () (add-hook 'after-save-hook 'dart-format-buffer nil t)))
  (add-hook 'flutter-test-mode-hook (lambda () (add-hook 'after-save-hook #'flutter-run-or-hot-reload nil t)))
  (add-hook 'flutter-mode-hook (lambda () (add-hook 'after-save-hook #'flutter-run-or-hot-reload nil t)))

  (with-eval-after-load 'projectile
    (add-to-list 'projectile-project-root-files-bottom-up "pubspec.yaml")
    (add-to-list 'projectile-project-root-files-bottom-up "BUILD"))

  (provide 'init-dart)
  ;;; init-dart.el ends here

#+end_src

**** Nix Customizations
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-nix-customizations.el :mkdirp yes
  ;;; init-nix-customizations.el --- Support Nix files -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (add-hook 'nix-ts-mode-hook ( lambda()(add-hook 'after-save-hook #'nixpkgs-fmt-buffer nil t) ))
  (add-hook 'nix-mode-hook ( lambda()(add-hook 'after-save-hook #'nixpkgs-fmt-buffer nil t) ))


  (provide 'init-nix-customizations)
  ;;; init-nix-customizations.el ends here

#+end_src

**** General
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-general.el :mkdirp yes
  ;;; init-general.el --- Provides shell  -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package general
    :config
    (general-create-definer efs/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "s-SPC")
    (efs/leader-keys
      "t"  '(:ignore t :which-key "TOGGLES")
      "tl" '(toggle-truncate-lines :which-key "Toggle Truncate Lines")))

  (unless (package-installed-p 'hydra)
    (package-install 'hydra))

  (defun rb/kill-del ()
    "Kill buffer and delete window."
    (interactive)
    (kill-this-buffer)
    (delete-window))
  ;;--------------------------------------------------------------------------------
  ;; Use ijkl to denote ↑←↓→ arrows.
  ;;--------------------------------------------------------------------------------
  (defhydra hydra-windows (global-map    "C-c w"            )
    "Choose Window Function:"
    ("b" balance-windows             "Balance"              )
    ("i" enlarge-window              "Heighten"             )
    ("e" shrink-window-horizontally  "Narrow"               )
    ("q" shrink-window               "Lower"                )
    ("m" enlarge-window-horizontally "Widen"                )
    ("a" ace-window                  "Number Based"         )
    ("r" rb/kill-del                 "Kill and Delete"      )
    ("d" delete-window               "Delete Window"        )
    ("s" split-window-vertically     "Horizontal Split"     )
    ("v" split-window-horizontally   "Vertical Split"       )
    ("h" windmove-left               "Move Left"            )
    ("j" windmove-down               "Move Down"            )
    ("k" windmove-up                 "Move Up"              )
    ("l" windmove-right              "Move Right"           )
    ("c" switch-window-then-swap-buffer  "Swap" :color teal))

  (efs/leader-keys
    "w" '(hydra-windows/body :which-key "WINDOW FUNCTIONS"))

  (defhydra hydra-buffers                (:timeout 20)
    "Choose Buffer Function:"
    ("h" buffer-flip-backward        "Backward"     )
    ("k" kill-this-buffer            "Kill Buffer"  )
    ("l" buffer-flip-forward         "Forward"      )
    ("f" nil "Finished"              :exit t       ))

  (efs/leader-keys
    "b" '(hydra-buffers/body :which-key "BUFFER FUNCTIONS"))

  (defhydra hydra-text-scale (:timeout 4)
    "Scale Text:"
    ("j" text-scale-increase "In")
    ("k" text-scale-decrease "Out")
    ("f" nil "Finished" :exit t))

  (efs/leader-keys
    "ts" '(hydra-text-scale/body :which-key "SCALE TEXT"))

  (defhydra hydra-projectile (:timeout 20)
    "Projectile Mode:"
    ("p" projectile-persp-switch-project   "Projectile Switch Project" )
    ("l" projectile-find-file              "Projectile Find File"      )
    ("k" projectile-project-run-cmd        "Projectile Run Project"    )
    ("t" projectile-project-test-cmd       "Projectile test Project"   )
    ("g" projectile-ripgrep                "Projectile Ripgrep Search" )
    ("m" projectile-commander              "Projectile Commander"      )
    ("a" persp-add-buffer                  "Perspective Add Buffer"    )
    ("s" persp-switch                      "Perspective Switch Project")
    ("r" persp-rename                      "Rename Perspective Tab"    )
    ("f" nil "Finished"                    :exit  t                   ))

  (efs/leader-keys
    "p" '(hydra-projectile/body :which-key "Perspective and Projectile"))
  (provide 'init-general)
  ;;; init-general.el ends here

#+end_src

**** Go
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-golang.el :mkdirp yes
  ;;; init-golang.el --- Support Golang files -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package go-mode
    :defer t
    :config
    (setq compile-command "echo Building... && go build -v && echo Testing... && go test -v && echo Linter... && golint")
    (setq compilation-scroll-output t
          compilation-window-height 14)
    (setq compilation-read-command nil))

  (add-hook 'go-mode-hook
            (lambda ()
              (local-set-key (kbd "M-,") 'compile)
              (local-set-key (kbd "M-.") 'godef-jump)))

  (add-hook 'before-save-hook 'gofmt-before-save)

  (unless (package-installed-p 'go-eldoc)
    (package-install 'go-eldoc))

  (add-hook 'go-mode-hook 'go-eldoc-setup)

  (set-face-attribute 'eldoc-highlight-function-argument nil
                      :underline t :foreground "green"
                      :weight 'bold)

  (provide 'init-golang)
  ;;; init-golang.el ends here

#+end_src

**** GraphQl
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-graphql.el :mkdirp yes
  ;;; init-graphql.el --- GraphQL integration -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package graphql-mode)

  (provide 'init-graphql)
  ;;; init-graphql.el ends here

#+end_src

**** Helpful
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-helpful.el :mkdirp yes
  ;;; init-helpful.el --- Provides helpful -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; helpful - a better way to view help messages
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package helpful
    ;; :custom
    :bind
    ([remap describe-function] . helpful-function)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-command] . helpful-command)
    ([remap describe-key] . helpful-key))

  (provide 'init-helpful)
  ;;; init-helpful.el ends here

#+end_src

**** Helpers
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-helper-packages.el :mkdirp yes
  ;;; init-helper-packages.el --- Support defaults -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:-

  (use-package undo-tree
    :diminish
    :config
    ;; Always have it on
    (global-undo-tree-mode)
    ;; Each node in the undo tree should have a timestamp.
    (setq undo-tree-visualizer-timestamps t)
    ;; Show a diff window displaying changes between undo nodes.
    (setq undo-tree-visualizer-diff t))

  (use-package emojify
    :config (setq emojify-display-style 'image)
    :init (global-emojify-mode 1)) ;; This will install missing images if needed.

  (use-package synosaurus
    :diminish synosaurus-mode
    :init    (synosaurus-mode)
    :config  (setq synosaurus-choose-method 'popup) ;; 'ido is default.
    (global-set-key (kbd "M-#") 'synosaurus-choose-and-replace))

  (use-package s)

  (use-package f)

  (use-package lorem-ipsum)

  (use-package origami
    ;; In Lisp languages, by default only function definitions are folded.
    :hook ((agda2-mode lisp-mode c-mode) . origami-mode)
    :config
    (push '(agda2-mode . (origami-markers-parser "{-" "-}"))
          origami-parser-alist))

  (use-package writegood-mode
    ;; Load this whenver I'm composing prose.
    :hook (text-mode org-mode)
    ;; Don't show me the “Wg” marker in the mode line
    :diminish
    ;; Some additional weasel words.
    :config
    (--map (push it writegood-weasel-words)
           '("some" "simple" "simply" "easy" "often" "easily" "probably"
             "clearly"               ;; Is the premise undeniably true?
             "experience shows"      ;; Whose? What kind? How does it do so?
             "may have"              ;; It may also have not!
             "it turns out that")))  ;; How does it turn out so?
  ;; ↯ What is the evidence of highighted phrase? ↯

  (use-package smartscan
    :defer t
    :config
    (global-set-key (kbd "M-'") 'rb/symbol-replace))

  (defun rb/symbol-replace (replacement)
    "REPLACEMENT of all standalone symbols in the buffer matching the one at point."
    (interactive  (list (read-from-minibuffer "Replacement for thing at point: " nil)))
    (save-excursion
      (let ((symbol (or (thing-at-point 'symbol) (error "No symbol at point!"))))
        (beginning-of-buffer)
        ;; (query-replace-regexp symbol replacement)
        (replace-regexp (format "\\b%s\\b" (regexp-quote symbol)) replacement))))

  (use-package goto-chg
    :defer t
    :custom (glc-default-span 0))

  ;; Yet another snippet extension program
  (use-package yasnippet
    :diminish yas-minor-mode
    :config
    ;; (yas-global-mode 1) ;; Always have this on for when using yasnippet syntax within yankpad
    ;; respect the spacing in my snippet declarations
    (setq yas-indent-line 'fixed))

  (use-package yasnippet-snippets)

  (use-package yankpad
    :defer 10
    :config
    (bind-key "<f9>" 'yankpad-map)
    (bind-key "<f12>" 'yankpad-expand)
    (bind-key "C-c s" 'yankpad-insert))

  (provide 'init-helper-packages)
  ;;; init-helper-packages.el ends here
#+end_src

**** Hydra
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-hydra.el :mkdirp yes
  ;;; init-hydra.el --- Support defaults -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;;--------------------------------------------------------------------------------
  ;; Invoke all possible key extensions having a common prefix by
  ;; supplying the prefix only once.
  ;;--------------------------------------------------------------------------------
  (unless (package-installed-p 'hydra)
    (package-install 'hydra))

  ;;--------------------------------------------------------------------------------
  ;; Neato doc strings for hydras
  ;;--------------------------------------------------------------------------------
  (unless (package-installed-p 'pretty-hydra)
    (package-install 'pretty-hydra))
  ;;--------------------------------------------------------------------------------
  ;; Hydra: Supply a prefix only once:2 ends here
  ;;--------------------------------------------------------------------------------

  (provide 'init-hydra)
  ;;; init-hydra.el ends here

#+end_src

**** Icons
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-icons.el :mkdirp yes
  ;;; init-icons.el --- Support defaults -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  ;; Only do this once:
  (when nil
    (use-package all-the-icons)
    (all-the-icons-install-fonts 'install-without-asking))

  ;; :-)
  ;; Make mail look pretty
  (use-package all-the-icons-gnus
    :defer t
    :config (all-the-icons-gnus-setup))

  (provide 'init-icons)
  ;;; init-icons.el ends here

#+end_src

**** Magit
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-magit.el :mkdirp yes
  ;;; init-magit.el --- Support Yaml files -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;; Purcell's legacy init-git.el may populate git-commit-mode-hook before
  ;; modern git-commit.el aliases that retired variable to
  ;; git-commit-setup-hook.  Move those functions first so defvaralias does
  ;; not overwrite the old value or emit a warning when Magit loads.
  (unless (featurep 'git-commit)
    (when (boundp 'git-commit-mode-hook)
      (dolist (function git-commit-mode-hook)
        (add-hook 'git-commit-setup-hook function))
      (makunbound 'git-commit-mode-hook)))

  ;; Git identity belongs to the system configuration.  Emacs must not mutate
  ;; global Git settings merely because Magit was loaded.

  ;; Keep commit-message and other ordinary Magit buffers in the selected
  ;; Emacs window. Diffs and process output may still use a second window.
  (with-eval-after-load 'magit
    (setq magit-display-buffer-function
          #'magit-display-buffer-same-window-except-diff-v1))

  ;; Use the emacsclient that belongs to this Emacs instance.  A launcher
  ;; script elsewhere on PATH must not add --create-frame or --no-wait to
  ;; Magit's commit-message requests.
  (with-eval-after-load 'with-editor
    (let ((client (expand-file-name "emacsclient" invocation-directory)))
      (when (file-executable-p client)
        (setq with-editor-emacsclient-executable client))))

  (defmacro rb/pretty-magit (WORD &optional ICON PROPS NO-PROMPT?)
    "Replace sanitised WORD with ICON, PROPS and by default add to prompts.
  Unless NO-PROMPT?"
    `(prog1
         (add-to-list 'pretty-magit-alist
                      (list (rx bow (group ,WORD (eval (if ,NO-PROMPT? "" ":"))))
                            ,ICON ',PROPS))
       (unless ,NO-PROMPT?
         (add-to-list 'pretty-magit-prompt (concat ,WORD ": ")))))

  (defmacro rb/pretty-magit-no-semi (WORD &optional ICON PROPS NO-PROMPT?)
    "Replace sanitised WORD with ICON, PROPS and by default add to prompts.
  Unless NO-PROMPT?"
    `(prog1
         (add-to-list 'pretty-magit-alist
                      (list (rx bow (group ,WORD (eval (if ,NO-PROMPT? "" ""))))
                            ,ICON ',PROPS))
       (unless ,NO-PROMPT?
         (add-to-list 'pretty-magit-prompt (concat ,WORD " ")))))
  ;; Set up who prompts on commit
  (setq pretty-magit-alist nil)
  (setq pretty-magit-prompt nil)
  (rb/pretty-magit "feat" "🆕")
  (rb/pretty-magit "docs" "📁")
  (rb/pretty-magit "fix" "🔨")
  (rb/pretty-magit "style" "🔭")
  (rb/pretty-magit "refactor" "🐰")
  ;; (rb/pretty-magit-no-semi "[Feat]" "🆕")
  ;; (rb/pretty-magit-no-semi "[Docs]" "📁")
  ;; (rb/pretty-magit-no-semi "[Fix]" "🔨")
  ;; (rb/pretty-magit-no-semi "[Style]" "🔭")
  ;; (rb/pretty-magit-no-semi "[Refactor]" "🐰")

  ;; TODO: Figure out why I can't use certain key bindings in magit commit buffer
  (defun add-magit-faces (&rest _args)
    "Add face properties and compose symbols for buffer from pretty-magit."
    (interactive)
    (with-silent-modifications
      (--each pretty-magit-alist
        (-let (((rgx icon props) it))
          (save-excursion
            (goto-char (point-min))
            (while (search-forward-regexp rgx nil t)
              (compose-region
               (match-beginning 1) (match-end 1) icon)
              (when props
                (add-face-text-property
                 (match-beginning 1) (match-end 1) props))))))))

  (advice-add 'magit-status :after 'add-magit-faces)
  (advice-add 'magit-refresh-buffer :after 'add-magit-faces)

  (setq use-magit-commit-prompt-p nil)

  (defun use-magit-commit-prompt (&rest args)
    (setq use-magit-commit-prompt-p t))

  (defun magit-commit-prompt ()
    "Magit prompt and insert commit header with faces."
    (interactive)
    (when use-magit-commit-prompt-p
      (setq use-magit-commit-prompt-p nil)
      (insert (completing-read "Commit Type " pretty-magit-prompt nil 'require-match ""))
      (add-magit-faces)
      (evil-insert 1)
      ))

  (remove-hook 'git-commit-setup-hook 'with-editor-usage-message)
  (add-hook 'git-commit-setup-hook 'magit-commit-prompt)
  (advice-add 'magit-commit :after 'use-magit-commit-prompt)

  ;; MA: The todo keywords work in code too!
  (use-package magit-todos
    :after magit
    :after hl-todo
    :hook (org-mode . magit-todos-mode)
    :config
    ;; For some reason cannot use :custom with this package.
    (custom-set-variables
     '(magit-todos-keywords (list "TODO" "FIXME" "MA" "WK" "JC")))
    ;; Ignore TODOs mentioned in exported HTML files; they're duplicated from org src.
    (setq magit-todos-exclude-globs '("*.html" "*.map"))
    (magit-todos-mode))

  (defun my/git-commit-reminder ()
    (insert "\n\n# The commit subject line ought to finish the phrase:
  # “If applied, this commit will ⟪your subject line here⟫.”")
    (beginning-of-buffer)
    (end-of-line))

  (add-hook 'git-commit-setup-hook 'my/git-commit-reminder)

  ;; Do not open a separate diff window when a commit message buffer appears.
  ;; The diff remains available on demand with C-c C-d.
  (with-eval-after-load 'magit-commit
    (remove-hook 'server-switch-hook #'magit-commit-diff)
    (remove-hook 'with-editor-filter-visit-hook #'magit-commit-diff))

  (provide 'init-magit)
  ;;; init-magit.el ends here

#+end_src

**** Master Settings
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-master.el :mkdirp yes
  ;;; init-master.el --- loads init-master.el -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  ;;--------------------------------------------------------------------------------
  ;; Wrap long lines when editing text
  ;;--------------------------------------------------------------------------------
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-auto-fill)

  ;;--------------------------------------------------------------------------------
  ;; Do not show the “Fill” indicator in the mode line.
  ;;--------------------------------------------------------------------------------
  (diminish 'auto-fill-function)

  ;;--------------------------------------------------------------------------------
  ;; Rebind the search keys to use consult
  ;;--------------------------------------------------------------------------------
  (global-set-key (kbd "C-r") 'consult-line)
  (global-set-key (kbd "C-s") 'consult-line)

  ;;--------------------------------------------------------------------------------
  ;; Bent arrows at the end and start of long lines.
  ;;--------------------------------------------------------------------------------
  (setq visual-line-fringe-indicators '(left-curly-arrow right-curly-arrow))
  (diminish 'visual-line-mode)
  (global-visual-line-mode 0)

  (when-let ((aspell (executable-find "aspell")))
    (setq ispell-program-name aspell)
    (use-package flyspell
      :diminish
      :hook ((prog-mode . flyspell-prog-mode)
             ((org-mode text-mode) . flyspell-mode))))

  (eval-after-load "flyspell"
    ' (progn
        (define-key flyspell-mouse-map [down-mouse-3] #'flyspell-correct-word)
        (define-key flyspell-mouse-map [mouse-3] #'undefined))) ;; set the default dictionary

  (global-font-lock-mode t)

  (custom-set-faces '(flyspell-incorrect ((t (:inverse-video t)))))
  (setq ispell-silently-savep t)

  (setq ispell-dictionary "en_GB")

  (setq ispell-personal-dictionary "~/.emacs.d/.aspell.en.pws")

  ;;--------------------------------------------------------------------------------
  (use-package wordnut
    :bind ("M-!" . wordnut-lookup-current-word))

  ;;--------------------------------------------------------------------------------
  ;; Use M-& for async shell commands.
  ;; Fix spelling as you type ---thesaurus & dictionary too!:11 ends here
  ;;--------------------------------------------------------------------------------
  (use-package speed-type :defer t)

  (use-package google-translate
    :defer t)

  ;;--------------------------------------------------------------------------------
  ;; Function used to clone repositories use Git
  ;;--------------------------------------------------------------------------------
  (cl-defun maybe-clone (remote &optional (local (concat "~/" (file-name-base remote))))
    "Clone a REMOTE repository if the LOCAL directory does not exist.

  Yields ‘repo-already-exists’ when no cloning transpires,
  otherwise yields ‘cloned-repo’.

  LOCAL is optional and defaults to the base name; e.g.,
  if REMOTE is https://github.com/X/Y then LOCAL becomes ~/Y."
    (if (file-directory-p local)
        'repo-already-exists
      (async-shell-command (concat "git clone " remote " " local))
      (add-to-list 'magit-repository-directories `(local   . 0))
      'cloned-repo))

  (use-package add-node-modules-path
    :custom
    (add-node-modules-path-command '("pnpm bin" "pnpm bin -w")))

  (eval-after-load 'js-mode
    '(add-hook 'js-mode-hook #'add-node-modules-path))

  ;;--------------------------------------------------------------------------------
  ;; Use a local LanguageTool installation when one is present.  Downloading
  ;; it is deliberately not a startup side effect.
  ;;--------------------------------------------------------------------------------
  (defconst rb/languagetool-jar
    (expand-file-name "LanguageTool/languagetool-commandline.jar"
                      user-emacs-directory))

  (when (file-exists-p rb/languagetool-jar)
    (use-package langtool
      :custom
      (langtool-language-tool-jar rb/languagetool-jar)))

  ;;--------------------------------------------------------------------------------
  ;; Quickly check, correct, then clean up /region/ with M-^
  ;;--------------------------------------------------------------------------------
  (eval-after-load 'langtool
    (progn
      (add-hook 'langtool-error-exists-hook
                (lambda ()
                  (langtool-correct-buffer)
                  (langtool-check-done)))

      (global-set-key "\M-^"
                      (lambda ()
                        (interactive)
                        (message "Grammar checking begun ...")
                        (langtool-check)))))

  (global-set-key (kbd "C-+") 'text-scale-increase)
  (global-set-key (kbd "C--") 'text-scale-decrease)

  (use-package editorconfig)

  (unless (package-installed-p 'editorconfig-generate)
    (package-install 'editorconfig-generate))

  (use-package hl-todo
    :config
    (mapc (lambda (x)
            (add-to-list 'hl-todo-keyword-faces (cons x "#dc8cc3")))
          '("TEST" "MA" "WK" "JC" "NOTE"))
    (global-hl-todo-mode))

  (defun add-watchwords () "Add TODO: words to font-lock keywords."
         (font-lock-add-keywords nil
                                 '(("\\(\\<TODO\\|\\<FIXME\\|\\<HACK\\|\\<NOTE\\|@.+\\):" 1
                                    font-lock-warning-face t))))

  (add-hook 'prog-mode-hook #'add-watchwords)


  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 4)

  (global-set-key "\M-k" #'(lambda () (interactive) (kill-line 0)) )

  (global-set-key (kbd "C-x k")
                  (lambda (&optional prefix)
                    "C-x k     ⇒ Kill current buffer & window
  C-u C-x k ⇒ Kill OTHER window and its buffer
  C-u C-u C-x C-k ⇒ Kill all other buffers and windows

  Prompt only if there are unsaved changes."
                    (interactive "P")
                    (pcase (or (car prefix) 0)
                      (0  (kill-this-buffer))
                      (4  (other-window 1)
                          (kill-this-buffer)
                          (unless (one-window-p) (delete-window)))
                      (16   (mapc 'kill-buffer (delq (current-buffer) (buffer-list)))
                            (delete-other-windows)))))

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package vimrc-mode
    :diminish)

  (use-package zlc
    :diminish)

  (use-package command-log-mode
    :diminish
    :config
    (setq global-command-log-mode t)
    (setq command-log-mode-auto-show t))

  (dolist (mode '(term-mode-hook
                  eshell-mode-hook
                  ielm-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))


  (provide 'init-master)
  ;;; init-master.el ends here

#+end_src

**** Navigation Settings
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-navigation.el :mkdirp yes
  ;;; init-navigation.el --- Support navigation commands -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package windmove
    :config
    (windmove-default-keybindings 'super)
    (setq windmove-wrap-around t))

  ;;----------------------------------------------------------------------------
  ;; Use super h,j,k,l for window navigation comparing to vim move keys
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "s-h") 'windmove-left)
  (global-set-key (kbd "s-[") 'windmove-left)
  (global-set-key (kbd "s-l") 'windmove-right)
  (global-set-key (kbd "M-]") 'windmove-right)
  (global-set-key (kbd "s-k") 'windmove-up)
  (global-set-key (kbd "s-j") 'windmove-down)
  (global-set-key (kbd "s-]") 'other-window)

  (use-package buffer-flip
    :config
    (setq buffer-flip-skip-patterns
          '("^\\*"
            "^magi"
            "COMMIT_EDIT MSG"
            ;; "^\\*Messages\\*\\b"
            )))

  ;;----------------------------------------------------------------------------
  ;; key to begin cycling buffers.
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "M-s-<tab>") 'buffer-flip-forward)
  (global-set-key (kbd "C-<tab>") 'buffer-flip-backward)

  ;;----------------------------------------------------------------------------
  ;; Let's get some keys to do splits both vertically and horizontally.
  ;; Let's also delete window with a more easier key
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "s-.") 'split-window-horizontally)
  (global-set-key (kbd "s-/") 'split-window-vertically)
  (global-set-key (kbd "s-;") 'delete-window)


  ;;----------------------------------------------------------------------------
  ;; Kill this buffer.
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "s-1")
                  (lambda ()
                    (interactive)
                    (kill-this-buffer)))

  ;;----------------------------------------------------------------------------
  ;; Kill buffer and close the current window.
  ;;----------------------------------------------------------------------------
  (global-set-key (kbd "s-r")
                  (lambda ()
                    (interactive)
                    (kill-this-buffer)
                    (delete-window)))

  ;;----------------------------------------------------------------------------
  ;; Great package for switching between windows
  ;;----------------------------------------------------------------------------
  (unless (package-installed-p 'ace-window)
    (package-install 'ace-window))

  (global-set-key (kbd "M-{") 'ace-window)

  (provide 'init-navigation)
  ;;; init-navigation.el ends here

#+end_src

**** Org Mode
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-org-customizations.el :mkdirp yes
  ;;; init-org-customizations.el --- Org-mode config -*- lexical-binding: t -*-
  ;;; Commentary:

  ;; Among settings for many aspects of `org-mode', this code includes
  ;; an opinionated setup for the Getting Things Done (GTD) system based
  ;; around the Org Agenda.  I have an "inbox.org" file with a header
  ;; including

  ;;     #+CATEGORY: Inbox
  ;;     #+FILETAGS: INBOX

  ;; and then set this file as `org-default-notes-file'.  Captured org
  ;; items will then go into this file with the file-level tag, and can
  ;; be refiled to other locations as necessary.

  ;; Those other locations are generally other org files, which should
  ;; be added to `org-agenda-files-list' (along with "inbox.org" org).
  ;; With that done, there's then an agenda view, accessible via the
  ;; `org-agenda' command, which gives a convenient overview.
  ;; `org-todo-keywords' is customised here to provide corresponding
  ;; TODO states, which should make sense to GTD adherents.

  ;;; Code:

  (use-package org-noter)

  ;; Fontify code in source blocks with the source language's major mode.
  (setq org-src-fontify-natively t
        org-src-tab-acts-natively t)

  ;; ATTENTION: org-noter-djvu needs the package ‘djvu’
  (unless (package-installed-p 'djvu)
    (package-install 'djvu))

  ;; ATTENTION: org-noter-nov needs the package ‘nov’
  (unless (package-installed-p 'nov)
    (package-install 'nov))

  ;; Various preferences
  (setq org-return-follows-link t
        org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done t
        org-agenda-skip-timestamp-if-done t
        org-agenda-tags-column 80
        ;; This shows the ‘Seinfeld consistency’ graph closer to the habit heading.
        org-habit-graph-column 50
        org-clock-history-length 23
        ;; Allow me to cycle through org files folded view from the beginning of
        ;; the file if no heading is on the first line.
        org-cycle-global-at-bob t
        org-clock-in-resume t
        org-archive-mark-done nil
        ;; Sometimes I change tasks I'm clocking quickly
        ;; ---this removes clocked tasks with 0:00 duration
        org-clock-out-remove-zero-time-clocks t
        ;; Clock out when moving task to a done state
        org-clock-out-when-done t
        ;; Save the running clock and all clock history
        ;; when exiting Emacs, load it on startup
        org-clock-persist t
        ;; Prompt to resume an active clock
        org-clock-persist-query-resume t
        ;; Include current clocking task in clock reports
        org-clock-report-include-clocking-task t
        ;; Show habits for every day in the agenda.
        org-habit-show-habits t
        org-habit-show-habits-only-for-today nil
        ;; Set org directory
        org-directory "~/Library/Containers/co.noteplan.NotePlan-setapp/Data/Library/Application Support/co.noteplan.NotePlan-setapp/Notes"
        ;; Set archive location
        org-archive-location "~/Library/Containers/co.noteplan.NotePlan-setapp/Data/Library/Application Support/co.noteplan.NotePlan-setapp/Notes/archive/%s_archive::* Archive")

  ;; (push '("Effort_ALL" . "0:15 0:30 0:45 1:00 2:00 3:00 4:00 5:00 6:00 0:00")
        ;; org-global-properties)

  ;;----------------------------------------------------------------------------
  ;; Let's get some fancy bullets
  ;;----------------------------------------------------------------------------
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode))

  (use-package toc-org
    ;; Use both “:ignore_N:” and ":export_N:” to exlude headings from the TOC.
    :custom (toc-org-noexport-regexp
             "\\(^*+\\)\s+.*:\\(ignore\\|noexport\\)\\([@_][0-9]\\)?:\\($\\|[^ ]*?:$\\)"))

  (if (require 'toc-org nil t)
      (progn
        (add-hook 'org-mode-hook 'toc-org-mode)

        ;; enable in markdown, too
        (add-hook 'markdown-mode-hook 'toc-org-mode)
        ;; (define-key markdown-mode-map (kbd "\C-c\C-o") 'toc-org-markdown-follow-thing-at-point))
        ))

  (add-to-list 'org-tag-alist '("TOC_5" . ?T))

  (use-package org-sticky-header
    :hook (org-mode . org-sticky-header-mode)
    :config
    (setq-default
     org-sticky-header-full-path 'full
     ;; Child and parent headings are seperated by a /.
     org-sticky-header-outline-path-separator " / "))

  (defun rb/org-goto-line (line)
    "Go to the indicated LINE, unfolding the parent Org header.
  Implementation: Go to the line, then look at the 1st previous org
  header, now we can unfold it whence we do so, then we go back to
  the line we want to be at."
    (interactive "nEnter line: ")
    (goto-line line)
    (org-previous-visible-heading 1)
    (org-cycle)
    (goto-line line))


  (defun rb/org-fold-current-subtree-anywhere-in-it ()
    "Hide the current heading, while being anywhere inside it."
    (interactive)
    (save-excursion
      (org-narrow-to-subtree)
      (org-shifttab)
      (widen)))

  (add-hook 'org-mode-hook
            #'(lambda ()
                (local-set-key (kbd "C-c C-h") 'rb/org-fold-current-subtree-anywhere-in-it)
                (local-set-key (kbd "M-g M-g") 'rb/org-goto-line)))

  (defvar init-rb-org-at-src-begin -1
    "Variable that holds whether last position was a.")

  (defvar init-rb-ob-header-symbol ?☰
    "Symbol used for babel headers.")

  (defun rb-org-prettify-src--update ()
    (let ((case-fold-search t)
          (re "^[ \t]*#\\+begin_src[ \t]+[^ \f\t\n\r\v]+[ \t]*")
          found)
      (save-excursion
        (goto-char (point-min))
        (while (re-search-forward re nil t)
          (goto-char (match-end 0))
          (let ((args (org-trim
                       (buffer-substring-no-properties (point)
                                                       (line-end-position)))))
            (when (org-string-nw-p args)
              (let ((new-cell (cons args init-rb-ob-header-symbol)))
                (cl-pushnew new-cell prettify-symbols-alist :test #'equal)
                (cl-pushnew new-cell found :test #'equal)))))
        (setq prettify-symbols-alist
              (cl-set-difference prettify-symbols-alist
                                 (cl-set-difference
                                  (cl-remove-if-not
                                   (lambda (elm)
                                     (eq (cdr elm) init-rb-ob-header-symbol))
                                   prettify-symbols-alist)
                                  found :test #'equal)))
        ;; Clean up old font-lock-keywords.
        (font-lock-remove-keywords nil prettify-symbols--keywords)
        (setq prettify-symbols--keywords (prettify-symbols--make-keywords))
        (font-lock-add-keywords nil prettify-symbols--keywords)
        (while (re-search-forward re nil t)
          (font-lock-flush (line-beginning-position) (line-end-position))))))

  (defun init-rb-org-prettify-src ()
    "Hide src options via `prettify-symbols-mode'.

    `prettify-symbols-mode' is used because it has uncollpasing.
    It's may not be efficient."
    (let* ((case-fold-search t)
           (at-src-block (save-excursion
                           (beginning-of-line)
                           (looking-at "^[ \t]*#\\+begin_src[ \t]+[^ \f\t\n\r\v]+[ \t]*"))))
      ;; Test if we moved out of a block.
      (when (or (and init-rb-org-at-src-begin
                     (not at-src-block))
                ;; File was just opened.
                (eq init-rb-org-at-src-begin -1))
        (rb-org-prettify-src--update))
      (setq init-rb-org-at-src-begin at-src-block)))

  (defun init-rb-org-prettify-symbols ()
    "Prettify source code openers in `org-mode'."
    (mapc (apply-partially 'add-to-list 'prettify-symbols-alist)
          (cl-reduce 'append
                     (mapcar (lambda (x) (list x (cons (upcase (car x)) (cdr x))))
                             `(("#+begin_src" . ?✎) ;; ➤ 🖝 ➟ ➤ ✎
                               ("#+end_src"   . ?□) ;; ⏹
                               ("#+header:" . ,init-rb-ob-header-symbol)
                               ("#+begin_quote" . ?»)
                               ("#+end_quote" . ?«)))))
    (turn-on-prettify-symbols-mode)
    (add-hook 'post-command-hook 'init-rb-org-prettify-src t t))


  (add-hook 'org-mode-hook #'init-rb-org-prettify-symbols)

  (global-prettify-symbols-mode)

  (defvar rb/prettify-alist nil
    "Musa's personal prettifications.")

  (cl-loop for pair in '(;; Example of how pairs like this to beautify org block delimiters
                         ("#+begin_example" . (?ℰ (Br . Bl) ?⇒)) ;; ℰ⇒
                         ("#+end_example"   . ?⇐)                 ;; ⇐
                         ("<=" . ?≤) (">=" . ?≥)
                         ("->" . ?→) ("-->". ?⟶) ;; threading operators
                         ("[ ]" . ?□) ("[X]" . ?☑) ("[-]" . ?◐)) ;; Org checkbox symbols

           do (push pair rb/prettify-alist))

  (cl-loop for hk in '(text-mode-hook prog-mode-hook org-mode-hook)
           do (add-hook hk (lambda ()
                             (setq prettify-symbols-alist
                                   (append rb/prettify-alist prettify-symbols-alist)))))

  (setq prettify-symbols-unprettify-at-point 'right-edge)

  (use-package org-pretty-tags
    :diminish org-pretty-tags-mode
    :config
    (setq org-pretty-tags-surrogate-strings
          '(("Neato"    . "💡")
            ("Blog"     . "✍")
            ("Audio"    . "♬")
            ("Video"    . "📺")
            ("Book"     . "📚")
            ("Running"  . "🏃")
            ("Question" . "❓")
            ("Wife"     . "💕")
            ("Text"     . "💬") ; 📨 📧
            ("Friends"  . "👪")
            ("Self"     . "🍂")
            ("Finances" . "💰")
            ("Car"      . "🚗") ; 🚙 🚗 🚘
            ("Urgent"   . "🔥"))) ;; 📥 📤 📬
    (org-pretty-tags-global-mode 1))

  (setq org-lowest-priority ?D) ;; Now org-speed-eky ‘,’ gives 4 options
  (setq org-priority-faces
        '((?A :foreground "red" :weight bold)
          (?B :foreground "orange" :weight bold-italic)
          (?C :foreground "yellow" :weight bold-italic)
          (?D :foreground "green" :weight bold-italic)))

  (use-package org-fancy-priorities
    :diminish t
    :hook   (org-mode . org-fancy-priorities-mode)
    :custom (org-fancy-priorities-list '("HIGH" "MID" "LOW" "OPTIONAL")))

  ;; Tasks get a 25 minute count down timer
  (setq org-timer-default-timer 25)

  ;; Use the timer we set when clocking in happens.
  (add-hook 'org-clock-in-hook
            (lambda () (org-timer-set-timer '(16))))

  ;; unless we clocked-out with less than a minute left,
  ;; show disappointment message.
  (add-hook 'org-clock-out-hook
            (lambda ()
              (unless (s-prefix? "0:00" (org-timer-value-string))
                (message-box "The basic 25 minutes on this difficult task are not up; it's a shame to see you leave."))
              (org-timer-stop)))

  (setq org-log-note-clock-out t)

  ;; Resume clocking task when emacs is restarted
  (org-clock-persistence-insinuate)


  (setq org-todo-keywords
        (quote ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d@)" "CANCELLED(c@)")
                (sequence "HABIT(a@)" "ROUTINE(r@)" "|" "DONE(d@)" "CANCELLED(c@)")
                (sequence "PROJECT(p@)" "|" "STARTED(s@)" "DONE(d@)" "CANCELLED(c@)")
                (sequence "WAITING(w@)" "DELEGATED(e@)" "HOLD(h@)" "|" "CANCELLED(c@)")))
        org-todo-repeat-to-state "NEXT")

  (setq org-todo-keyword-faces
        (quote (("NEXT" :inherit warning)
                ("DONE" :inherit font-lock-comment-face)
                ("STEP_6" . (:foreground "red" :weight bold))
                ("HABIT" . (:foreground "coral" :weight bold))
                ("Q2" . (:foreground "magenta3" :weight bold))
                ("Q3" . (:foreground "DeepPink" :weight bold))
                ("Q4" . (:foreground "OrangeRed" :weight bold))
                ("STEP_4" . (:foreground "coral" :weight bold))
                ("Q1" . (:foreground "SeaGreen1" :weight bold))
                ("TODO" . (:foreground "LimeGreen" :weight bold))
                ("GOAL" . (:foreground "turquoise1" :weight bold))
                ("HOLD" . (:foreground "chocolate4" :weight bold))
                ("STEP_5" . (:foreground "OrangeRed" :weight bold))
                ("STARTED" . (:foreground "magenta3" :weight bold))
                ("STEP_2" . (:foreground "IndianRed" :weight bold))
                ("PLANNER" . (:foreground "LimeGreen" :weight bold))
                ("LIFE_GOAL" . (:foreground "SkyBlue" :weight bold))
                ("STEP_3" . (:foreground "IndianRed1" :weight bold))
                ("WAITING" . (:foreground "firebrick4" :weight bold))
                ("CANCELLED" . (:foreground "DeepPink" :weight bold))
                ("ROUTINE" . (:foreground "PaleGreen1" :weight bold))
                ("PROJECT" . (:foreground "DodgerBlue1" :weight bold))
                ("DELEGATED" . (:foreground "turquoise1" :weight bold))
                ("ALL_YEAR" . (:foreground "systemBlueColor" :weight bold))
                )))

  (setq org-agenda-compact-blocks t
        org-agenda-sticky t
        org-agenda-start-on-weekday nil
        org-agenda-span 'day
        org-agenda-include-diary nil
        org-agenda-sorting-strategy
        '((agenda habit-down time-up user-defined-up effort-up category-keep)
          (todo category-up effort-up)
          (tags category-up effort-up)
          (search category-up))
        org-agenda-window-setup 'current-window
        org-agenda-custom-commands
        `(("N" "Notes" tags "NOTE"
           ((org-agenda-overriding-header "Notes")
            (org-tags-match-list-sublevels t)))
          ("p" "Planner"
           ((tags "STEPS"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "WEEKLY PLANNER!!!")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_1"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "MY BIGGEST WINS")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_2"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "AFTER ACTION REVIEW")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_3"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "LIST SWEEP")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_4"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "WEEKLY OVERVIEW")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_5"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "WEEKLY BIG 3")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))
            (tags "STEP_6"
                  ((org-agenda-files org-planning-agenda-files)
                   (org-agenda-overriding-header "SELF CARE PLANNER")
                   (org-tags-match-list-sublevels t)
                   (org-tags-match-list-sublevels 'indented)))))
          ("G" "GOALS"
           ((todo "GOAL"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "GOALS")
                   (org-tags-match-list-sublevels nil)))
            (todo "Q1"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "FIRST QUARTER")
                   (org-tags-match-list-sublevels nil)))
            (todo "Q2"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "SECOND QUARTER")
                   (org-tags-match-list-sublevels nil)))
            (todo "Q3"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "THIRD QUARTER")
                   (org-tags-match-list-sublevels nil)))
            (todo "Q4"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "LAST QUARTER")
                   (org-tags-match-list-sublevels nil)))
            (todo "ALL_YEAR"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "ALL YEAR")
                   (org-tags-match-list-sublevels nil)))
            (todo "STARTED"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "STARTED")
                   (org-tags-match-list-sublevels nil)))
            (todo "LIFE_GOAL"
                  ((org-agenda-files org-goals-files)
                   (org-agenda-overriding-header "LIFE GOALS")
                   (org-tags-match-list-sublevels nil)))))
          ("h" "Habits"
           ((tags-todo "MORNING"
                       ((org-agenda-files org-habits-files)
                        (org-agenda-overriding-header "MORNING ROUTINES")
                        (org-tags-match-list-sublevels nil)))
            (tags-todo "MIDDAY"
                       ((org-agenda-files org-habits-files)
                        (org-agenda-overriding-header "MIDDAY ROUTINES")
                        (org-tags-match-list-sublevels nil)))
            (tags-todo "EVENING"
                       ((org-agenda-files org-habits-files)
                        (org-agenda-overriding-header "EVENING ROUTINES")
                        (org-tags-match-list-sublevels nil)))
            (tags-todo "WEEKEND"
                       ((org-agenda-files org-habits-files)
                        (org-agenda-overriding-header "WEEKEND ROUTINES")
                        (org-tags-match-list-sublevels nil)))
            (todo "HABIT"
                  ((org-agenda-files org-habits-files)
                   (org-agenda-overriding-header "HABIT")
                   (org-tags-match-list-sublevels nil)))))
          ("g" "GTD"
           ((agenda "" nil)
            (tags "INBOX"
                  ((org-agenda-overriding-header "Inbox")
                   (org-tags-match-list-sublevels nil)
                   (org-agenda-skip-function
                    #'(lambda ()
                        (org-agenda-skip-subtree-if 'todo '("DONE" "HOLD"))))))
            (stuck ""
                   ((org-agenda-overriding-header "Stuck Projects")
                    (org-agenda-tags-todo-honor-ignore-options t)
                    (org-tags-match-list-sublevels t)
                    (org-agenda-todo-ignore-scheduled 'future)))
            (tags-todo "-INBOX"
                       ((org-agenda-overriding-header "Next Actions")
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-skip-function
                         #'(lambda ()
                             (or (org-agenda-skip-subtree-if 'todo '("HOLD" "WAITING"))
                                 (org-agenda-skip-entry-if 'nottodo '("NEXT")))))
                        (org-tags-match-list-sublevels t)
                        (org-agenda-sorting-strategy
                         '(todo-state-down effort-up category-keep))))
            (tags-todo "-INBOX/-NEXT"
                       ((org-agenda-overriding-header "Orphaned Tasks")
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-skip-function
                         #'(lambda ()
                             (or (org-agenda-skip-subtree-if
                                  'todo
                                  '(
                                    "DELEGATED"
                                    "HABIT"
                                    "HOLD"
                                    "PLANNER"
                                    "PROJECT"
                                    "ROUTINE"
                                    "STEP_1"
                                    "STEP_2"
                                    "STEP_3"
                                    "STEP_4"
                                    "STEP_5"
                                    "STEP_6"
                                    "WAITING"))
                                 (org-agenda-skip-subtree-if 'nottododo '("TODO")))))
                        (org-tags-match-list-sublevels t)
                        (org-agenda-sorting-strategy
                         '(category-keep))))
            (tags-todo "/WAITING"
                       ((org-agenda-overriding-header "Waiting")
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-sorting-strategy
                         '(category-keep))))
            (tags-todo "/DELEGATED"
                       ((org-agenda-overriding-header "Delegated")
                        (org-agenda-tags-todo-honor-ignore-options t)
                        (org-agenda-todo-ignore-scheduled 'future)
                        (org-agenda-sorting-strategy
                         '(category-keep))))
            (tags-todo "/HOLD"
                       ((org-agenda-overriding-header "On Hold")
                        (org-agenda-skip-function
                         #'(lambda ()
                             (or (org-agenda-skip-subtree-if 'todo '("WAITING"))
                                 (org-agenda-skip-entry-if 'nottodo '("HOLD")))))
                        (org-tags-match-list-sublevels nil)
                        (org-agenda-sorting-strategy
                         '(category-keep))))
            ;; (tags-todo "-NEXT"
            ;;            ((org-agenda-overriding-header "All other TODOs")
            ;;             (org-match-list-sublevels t)))
            ))))

  (require 'org-tempo)

  (push '("conf-unix" . conf-unix) org-src-lang-modes)

  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("rb" . "src ruby"))
  (add-to-list 'org-structure-template-alist '("ni" . "src nix"))

  (defun org-global-props (&optional rb/property)
    "Get the plists of global org properties of current buffer."
    (interactive)
    (unless rb/property (setq rb/property "PROPERTY"))
    (org-element-map (org-element-parse-buffer)
        'keyword (lambda (el) (when (string-match rb/property (org-element-property :key el)) el))))

  (defun org-global-prop-value (key)
    "Get global org property KEY of current buffer."
    (org-element-property :value (car (org-global-props key))))

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    "Used to tangle org file when it change."
    (when (or (string-equal (file-name-directory (buffer-file-name))
                            (expand-file-name user-emacs-directory))
              (equal (org-global-prop-value "CATEGORY") "Configuration"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  ;; Tangling is handled during the Nix build so deployed files remain immutable.

  (when (file-exists-p "~/.emacs.d/plantuml.jar")
    (setq org-plantuml-jar-path
          (expand-file-name  "~/.emacs.d/plantuml.jar"))

    (setq org-confirm-babel-evaluate nil))
  ;;----------------------------------------------------------------------------
  ;; I'm making the checkbox feature work with bullets as well as the normal way.
  ;; I copied this code from Sasha Chua at:
  ;; https://sachachua.com/blog/2008/01/outlining-your-notes-with-org/
  ;;----------------------------------------------------------------------------
  (defun wicked/org-update-checkbox-count (&optional all)
    "Update the checkbox statistics in the current section.
  This will find all statistic cookies like [57%] and [6/12] and
  update them with the current numbers.  With optional prefix
  argument ALL, do this for the whole buffer."
    (interactive "P")
    (save-excursion
      (let* (              ; (buffer-invisibility-spec (org-inhibit-invisibility))
             (beg (condition-case nil
                      (progn (outline-back-to-heading) (point))
                    (error (point-min))))
             (end (move-marker
                   (make-marker)
                   (progn (or (outline-get-next-sibling) ;; (1)
                              (goto-char (point-max)))
                          (point))))
             (re "\\(\\[[0-9]*%\\]\\)\\|\\(\\[[0-9]*/[0-9]*\\]\\)")
             (re-box
              "^[ \t]*\\(*+\\|[-+*]\\|[0-9]+[.)]\\) +\\(\\[[- X]\\]\\)")
             b1 e1 f1 c-on c-off lim (cstat 0))
        (when all
          (goto-char (point-min))
          (or (outline-get-next-sibling) (goto-char (point-max))) ;; (2)
          (setq beg (point) end (point-max)))
        (goto-char beg)
        (while (re-search-forward re end t)
          (setq cstat (1+ cstat)
                b1 (match-beginning 0)
                e1 (match-end 0)
                f1 (match-beginning 1)
                lim (cond
                     ((org-on-heading-p)
                      (or (outline-get-next-sibling) ;; (3)
                          (goto-char (point-max)))
                      (point))
                     ((org-at-item-p) (org-end-of-item) (point))
                     (t nil))
                c-on 0 c-off 0)
          (goto-char e1)
          (when lim
            (while (re-search-forward re-box lim t)
              (if (member (match-string 2) '("[ ]" "[-]"))
                  (setq c-off (1+ c-off))
                (setq c-on (1+ c-on))))
            (goto-char b1)
            (insert (if f1
                        (format "[%d%%]" (/ (* 100 c-on)
                                            (max 1 (+ c-on c-off))))
                      (format "[%d/%d]" c-on (+ c-on c-off))))
            (and (looking-at "\\[.*?\\]")
                 (replace-match ""))))
        (when (interactive-p)
          (message "Checkbox statistics updated %s (%d places)"
                   (if all "in entire file" "in current outline entry")
                   cstat)))))
  (defadvice org-update-checkbox-count (around wicked activate)
    "Fix the built-in checkbox count to understand headlines."
    (setq ad-return-value
          (wicked/org-update-checkbox-count (ad-get-arg 1))))

  (require 'epa-file)
  (epa-file-enable)

  (require 'org-crypt)
  (org-crypt-use-before-save-magic)
  (setq org-tags-exclude-from-inheritance (quote ("crypt")))
  ;; GPG key to use for encryption
  ;; Either the Key ID or set to nil to use symmetric encryption.
  (setq org-crypt-key "306FAA9223DD193A")

  ;; This fixes the problem where org-crypt make org-babel-tangle fail
  ;; because src blocks are encrypted before babel runs.
  ;; Thanks to https://ag91.github.io/blog/2020/10/30/org-crypt-and-tangling-source-blocks/
  (defun rb/reveal-and-move-back ()
    (org-reveal)
    (goto-char rb/old-point))
  (defun rb/org-reveal-after-save-on ()
    (setq rb/old-point (point))
    (add-hook 'after-save-hook 'rb/reveal-and-move-back))
  (defun rb/org-reveal-after-save-off ()
    (remove-hook 'after-save-hook 'rb/reveal-and-move-back))
  (add-hook 'org-babel-pre-tangle-hook 'rb/org-reveal-after-save-on)
  (add-hook 'org-babel-post-tangle-hook 'rb/org-reveal-after-save-off)

  ;; Set org-modules I want to use
  (setq org-modules
        '(ol-bbdb
          ol-bibtex
          org-crypt
          ol-docview
          ol-eww
          ol-gnus
          org-habit
          ol-info
          ol-irc
          ol-rmail
          ol-w3m
          ol-eshell))

  (use-package async)

  (use-package ob-async
    :init
    (setq ob-async-no-async-languages-alist '("ipython")))

  ;; This allows you to tell org-babel to tangle you org files after
  ;; save by placing:
  ;; #+CATEGORY: Configuration
  ;; in the head of the org file.
  ;; Change this search key/term to what best suits the individual
  (setq efs/tangle-search-key "CATEGORY")
  (setq efs/tangle-search-term "Configuration")

  (defun efs/org-global-props (&optional efs/property)
    "Get the plists of global org properties of current buffer."
    (interactive)
    (unless efs/property (setq efs/property "PROPERTY"))
    (org-element-map (org-element-parse-buffer)
        'keyword (lambda (el) (when (string-match efs/property (org-element-property :key el)) el))))

  (defun efs/org-global-prop-value (key)
    "Get global org property KEY of current buffer."
    (org-element-property :value (car (efs/org-global-props key))))

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    "Used to tangle org file when it change."
    (when (or (string-equal (file-name-directory (buffer-file-name))
                            (expand-file-name user-emacs-directory))
              (string-equal (efs/org-global-prop-value efs/tangle-search-key) efs/tangle-search-term))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  ;;; (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))
  ;; Tangling is handled during the Nix build so deployed files remain immutable.

  (defun org-invoice-generate ()
    (interactive)

                                          ; Activate Org Column Advice
    (defadvice org-table-goto-column
        (before
         always-make-new-columns
         (n &optional on-delim force)
         activate)
      "Always adds new columns for table formulae"
      (setq force t))

                                          ; Save Cursor Position
    (point-to-register ?a)

                                          ; Ignore Lisp Code in Search
    (beginning-of-buffer)
    (search-forward "#+NAME: startup")
    (let ((pos (point)))
      (beginning-of-buffer)
                                          ; Search for LaTex Attributes
      (search-forward "#+TBLNAME: services" pos)
      (let ((latex (condition-case nil
                       (search-forward "#+ATTR_LATEX:" pos)
                     (error nil))))

                                          ; Copy LaTeX Attributes
                                          ; (`org-prepare-dblock` removes them
                                          ;  as they are inside the dblock)
        (if latex
            (progn
              (move-beginning-of-line 1)
              (kill-line)))
                                          ; Generate Services Breakdown
        (search-backward "#+TBLNAME: services")
        (forward-line 1)
        (org-dblock-update)

                                          ; Restore LaTeX Attributes
        (if latex
            (progn
              (forward-line 1)
              (yank)
              (newline))))
                                          ; Update Balance Due
      (search-forward "#+BEGIN: table")
      (forward-line 2)
      (org-table-recalculate))

                                          ; Deactivate Org Column Advice
    (ad-deactivate 'org-table-goto-column)

    (org-table-recalculate-buffer-tables)
                                          ; Restore Cursor Position
    (jump-to-register ?a))



  (provide 'init-org-customizations)
  ;;; init-org-customizations.el ends here

#+end_src

**** PDF Tools
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-pdf.el :mkdirp yes
  ;;; init-pdf.el --- PDF Configurations -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package pdf-tools
    :config
    (pdf-loader-install))

  (provide 'init-pdf)
  ;;; init-pdf.el ends here

#+end_src

**** Perspective
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-perspective.el :mkdirp yes
  ;;; init-perspective.el --- Provides omnisharp -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; perspective intellisense like bindings
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (defconst rb/perspective-state-directory
    (expand-file-name "persp-confs" user-emacs-directory))
  (make-directory rb/perspective-state-directory t)

  (require 'consult)

  (defun rb/current-buffer-git-root ()
    "Return the Git root associated with the current buffer, or nil."
    (let ((location
           (or (buffer-file-name (or (buffer-base-buffer) (current-buffer)))
               (and (derived-mode-p 'magit-mode 'dired-mode)
                    default-directory))))
      (and location (locate-dominating-file location ".git"))))

  (defun rb/current-perspective-buffer-list ()
    "Return live buffers belonging to the current perspective."
    (if (bound-and-true-p persp-mode)
        (persp-current-buffers*)
      (buffer-list)))

  (defun rb/consult-project-or-perspective-buffer ()
    "Preview and select a buffer from the current Git project or perspective."
    (interactive)
    (if-let ((root (rb/current-buffer-git-root)))
        (let ((consult-project-function (lambda (&optional _prompt) root)))
          (consult-project-buffer))
      (let ((consult-buffer-list-function #'rb/current-perspective-buffer-list))
        (consult-buffer '(consult-source-buffer)))))

  (with-eval-after-load 'consult
    (consult-customize rb/consult-project-or-perspective-buffer
                       :preview-key 'any))

  (use-package perspective
    :diminish
    :commands (persp-switch)
    :config
    (setq persp-state-default-file
          (expand-file-name "persp-auto-save" rb/perspective-state-directory))
    :custom
    (persp-mode-prefix-key (kbd "M-p"))
    :init
    (persp-mode)
    :bind (("s-s" . persp-switch)
           ("s-b" . rb/consult-project-or-perspective-buffer)
           ("C-x b" . persp-switch-to-buffer*)
           ("C-x k" . persp-kill-buffer*)))

  (add-hook 'kill-emacs-hook #'persp-state-save)

  (use-package persp-projectile
    :bind (("s-p" . projectile-persp-switch-project)))


  (provide 'init-perspective)
  ;;; init-perspective.el ends here

#+end_src

**** Plant UML
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-plantuml.el :mkdirp yes
  ;;; init-plantuml.el --- Provides plantuml-mode -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; plantuml like bindings
  ;;; Code:

  (unless (package-installed-p 'plantuml-mode)
    (package-install 'plantuml-mode))

  (setq plantuml-path "~/.emacs.d/plantuml.jar")

  (when (file-exists-p plantuml-path)
    (setq plantuml-jar-path plantuml-path)
    (setq plantuml-default-exec-mode 'jar))

  ;; Enable plantuml-mode for PlantUML files
  (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode))

  (add-to-list
   'org-src-lang-modes '("plantuml" . plantuml))

  (setq plantuml_helper_path "~/.emacs.d/site-lisp/plantuml_helpers.el")

  (setq plantuml-dw-cmd
        (concat
         "curl "
         " -LO "
         "https://gist.githubusercontent.com/"
         "Randy1Burrell/7ed8899da46f2c73564a6103e419aa32/"
         "raw/d1bf8c898af7ea1a0f294087059dc76a6521f4d2/plantuml_helpers.el"))

  (when (not (file-exists-p plantuml_helper_path))
    (shell-command-to-string plantuml-dw-cmd)
    (unless (file-exists-p plantuml_helper_path)
      (shell-command-to-string
       "mv plantuml_helpers.el ~/.emacs.d/site-lisp/"))
    (when (file-exists-p plantuml_helper_path)
      (add-to-list 'load-path plantuml_helper_path)
      (require 'plantuml_helpers)))

  (provide 'init-plantuml)
  ;;; init-plantuml.el ends here

#+end_src

**** Prisma
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-prisma.el :mkdirp yes
  ;;; init-prisma.el --- Prisma integration -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package prisma-ts-mode)

  (defun rb/prisma-mode ()
    "Add some file to `auto-mode-alist'."
    (mapc
     (lambda (x)
       (add-to-list 'auto-mode-alist (cons x 'prisma-mode)))
     '("\\.prisma\\'")))

  (rb/prisma-mode)

  (setq prisma-format-on-save t)

  ;; (add-hook 'prisma-mode-hook 'lsp-mode)

  (provide 'init-prisma)
  ;;; init-prisma.el ends here

#+end_src

**** Projectile
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-projectile-customizations.el :mkdirp yes
  ;;; init-projectile-customizations.el --- Use Projectile for navigation within projects -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (provide 'init-projectile-customizations)
  ;;; init-projectile-customizations.el ends here

#+end_src

**** Protobuf
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-protobuf.el :mkdirp yes
  ;;; init-protobuf.el --- Sets up mode for writing protocol buffer -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package protobuf-mode)

  (provide 'init-protobuf)
  ;;; init-protobuf.el ends here

  #+end_src

**** Restart Emacs
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-restart-emacs.el :mkdirp yes
  ;;; init-restart-emacs.el --- loads restart-emacs package -*- lexical-binding: t -*-

  ;;; Commentary:
  ;; Provides only the command “restart-emacs”.

  ;;; Code:

  (unless (package-installed-p 'restart-emacs)
    (package-install 'restart-emacs))

  (provide 'init-restart-emacs)
  ;;; init-restart-emacs.el ends here

#+end_src

**** Rust
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-rust-customizations.el :mkdirp yes
  ;;; init-rust-customizations.el --- Support for the Rust language -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (when (maybe-require-package 'rust-mode)
    (with-eval-after-load 'rust-mode
      (setq rust-mode-treesitter-derive t)
      (setq rust-format-on-save t)
      (add-hook 'rust-mode-hook (lambda () (setq indent-tabs-mode nil)))))

  (use-package cargo-mode
    :hook
    (rust-mode . cargo-minor-mode)
    :config
    (setq compilation-scroll-output t))

  (provide 'init-rust-customizations)
  ;;; init-rust-customizations.el ends here
#+end_src

**** Security
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-security.el :mkdirp yes
  ;;; init-security.el --- Security tools -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code

  (setq epg-gpg-program "gpg2")
  (setenv "GPG_AGENT_INFO" nil)
  (setq auth-sources '("~/.emacs.d/secrets/.authinfo.gpg"))

  (provide 'init-security)
  ;;; init-security.el ends here

#+end_src

**** Sessions
#+begin_src emacs-lisp :tangle ~/.emacs.d/lisp/init-sessions.el :mkdirp yes
  ;;; init-sessions.el --- Save and restore editor sessions between restarts -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;; save a list of open files in ~/.emacs.d/.emacs.desktop
  (setq desktop-path (list user-emacs-directory)
        desktop-auto-save-timeout 600)
  ;; Disable sessions here because it interferes with perspective
  (desktop-save-mode 0)

  (defun sanityinc/desktop-time-restore (orig &rest args)
    (let ((start-time (current-time)))
      (prog1
          (apply orig args)
        (message "Desktop restored in %.2fms"
                 (sanityinc/time-subtract-millis (current-time)
                                                 start-time)))))
  (advice-add 'desktop-read :around 'sanityinc/desktop-time-restore)

  (defun sanityinc/desktop-time-buffer-create (orig ver filename &rest args)
    (let ((start-time (current-time)))
      (prog1
          (apply orig ver filename args)
        (message "Desktop: %.2fms to restore %s"
                 (sanityinc/time-subtract-millis (current-time)
                                                 start-time)
                 (when filename
                   (abbreviate-file-name filename))))))
  (advice-add 'desktop-create-buffer :around 'sanityinc/desktop-time-buffer-create)

  
  ;; Restore histories and registers after saving

  (setq-default history-length 1000)
  (add-hook 'after-init-hook 'savehist-mode)

  (require-package 'session)

  (setq session-save-file (locate-user-emacs-file ".session"))
  (setq session-name-disable-regexp "\\(?:\\`'/tmp\\|\\.git/[A-Z_]+\\'\\)")
  (setq session-save-file-coding-system 'utf-8)

  (add-hook 'after-init-hook 'session-initialize)

  ;; save a bunch of variables to the desktop file
  ;; for lists specify the len of the maximal saved data also
  (setq desktop-globals-to-save
        '((comint-input-ring        . 50)
          (compile-history          . 30)
          desktop-missing-file-warning
          (dired-regexp-history     . 20)
          (extended-command-history . 30)
          (face-name-history        . 20)
          (file-name-history        . 100)
          (grep-find-history        . 30)
          (grep-history             . 30)
          (magit-revision-history   . 50)
          (minibuffer-history       . 50)
          (org-clock-history        . 50)
          (org-refile-history       . 50)
          (org-tags-history         . 50)
          (query-replace-history    . 60)
          (read-expression-history  . 60)
          (regexp-history           . 60)
          (regexp-search-ring       . 20)
          register-alist
          (search-ring              . 20)
          (shell-command-history    . 50)
          tags-file-name
          tags-table-list))


  (provide 'init-sessions)
  ;;; init-sessions.el ends here

#+end_src
**** Shell
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-shell.el :mkdirp yes
  ;;; init-shell.el --- Provides shell  -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; Provides zsh shell script completion
  ;;; Code:

  (use-package term
    :config
    (setq explicit-shell-file-name "zsh") ;; Change this to zsh, etc
    ;;(setq explicit-zsh-args '())         ;; Use 'explicit-<shell>-args for shell-specific args

    ;; Match the default Bash shell prompt.  Update this if you have a custom prompt
    ;; (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))
    )

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))

  (use-package vterm
    :commands vterm
    :config
    ;; (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    (setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

  (when (eq system-type 'windows-nt)
    (setq explicit-shell-file-name "powershell.exe")
    (setq explicit-powershell.exe-args '()))

  (defun rb/configure-eshell ()
    "Configure eshell."
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    ;; Bind some useful keys for evil-mode
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-a") 'eshell-bol)
    (evil-normalize-keymaps)

    (setq eshell-history-size         10000
          eshell-buffer-maximum-lines 10000
          eshell-hist-ignoredups t
          eshell-scroll-to-bottom-on-input t))

  (use-package eshell-git-prompt
    :diminish)

  (use-package eshell
    :hook (eshell-first-time-mode . rb/configure-eshell)
    :config
    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t))
    :init
    (eshell-git-prompt-use-theme 'powerline))

  (dolist (mode '(eshell-mode-hook))
    (add-hook mode 'with-editor-export-editor))


  (provide 'init-shell)
  ;;; init-shell.el ends here

#+end_src

**** Shell Path
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-exec-path-customizations.el :mkdirp yes
  ;;; init-exec-path-customizations.el --- Set up exec-path to help Emacs find programs  -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (require-package 'exec-path-from-shell)

  (with-eval-after-load 'exec-path-from-shell
    (dolist (var '("GOPATH"))
      (add-to-list 'exec-path-from-shell-variables var)))

  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize))

  (provide 'init-exec-path-customizations)
  ;;; init-exec-path-customisations.el ends here

#+end_src

**** Solidity
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-solidity.el :mkdirp yes
  ;;; init-solidity.el --- PDF Configurations -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package solidity-mode)

  (provide 'init-solidity)
  ;;; init-solidity.el ends here

#+end_src

**** SQL
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-sql-customizations.el :mkdirp yes
  ;;; init-sql-customizations.el --- Support for SQL -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;; Ask for port when I try to login to dbs (MySQL/PostgreSQL)
  (require 'sql)
  (setq sql-postgres-login-params (append sql-postgres-login-params '(port :default 5432)))
  (setq sql-mysql-login-params (append sql-mysql-login-params '(port :default 3306)))

  (setq-default sql-input-ring-file-name
                (expand-file-name ".sqli_history" user-emacs-directory))

  (provide 'init-sql-customizations)
  ;;; init-sql-customizations.el ends here

#+end_src

**** Straight
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-straight.el :mkdirp yes
  ;; init-straight.el --- Initialize straight.el -*- lexical-binding: t -*-
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (setq straight-use-package-by-default 'use-package)
  (straight-use-package 'use-package)

  (provide 'init-straight)
  ;;; init-straight.el ends here

#+end_src

**** Tailwind
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-tailwind.el :mkdirp yes
  ;;; init-tailwind.el --- Tailwind integration -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package lsp-tailwindcss
    :init
    (setq lsp-tailwindcss-experimental-class-regex ["tw`([^`]*)" "tw=\"([^\"]*)" "tw={\"([^\"}]*)" "tw\\.\\w+`([^`]*)" "tw\\(.*?\\)`([^`]*)"]
          lsp-tailwindcss-add-on-mode t)
    :config
    (add-to-list 'lsp-language-id-configuration '(".*\\.erb$" . "html")))

  ;; (add-hook 'before-save-hook 'lsp-tailwindcss-rustywind-before-save)

  (provide 'init-tailwind)
  ;;; init-tailwind.el ends here

#+end_src

**** Tramp
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-tramp.el :mkdirp yes
  ;;; init-tramp.el --- loads tramps package extras -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;; make sure you've set your default project with:
  ;; gcloud config set project <project-name>

  (require 'tramp)
  (add-to-list 'tramp-methods
               '("gcssh"
  (tramp-login-program        "gcloud beta compute ssh")
  (tramp-login-args           (("%h")))
  (tramp-async-args           (("-q")))
  (tramp-remote-shell         "/bin/sh")
  (tramp-remote-shell-args    ("-c"))
  (tramp-gw-args              (("-o" "GlobalKnownHostsFile=/dev/null")
                               ("-o" "UserKnownHostsFile=/dev/null")
                               ("-o" "StrictHostKeyChecking=no")))
  (tramp-default-port         22)))

  ;; ... after which it's as easy as:
  ;;
  ;; C-x C-f /gcssh:compute-instance:/path/to/filename.clj
  (provide 'init-tramp)
  ;;; init-tramp.el ends here

#+end_src

**** Treesitter
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-treesitter-customizations.el :mkdirp yes
  ;;; init-treesitter-customizations.el --- Treesit language -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (setq treesit-language-source-alist
        '((bash "https://github.com/tree-sitter/tree-sitter-bash")
          (cmake "https://github.com/uyha/tree-sitter-cmake")
          (css "https://github.com/tree-sitter/tree-sitter-css")
          (elisp "https://github.com/Wilfred/tree-sitter-elisp")
          (go "https://github.com/tree-sitter/tree-sitter-go")
          (gomod "https://github.com/camdencheek/tree-sitter-go-mod")
          (dockerfile "https://github.com/camdencheek/tree-sitter-dockerfile")
          (html "https://github.com/tree-sitter/tree-sitter-html")
          (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
          (json "https://github.com/tree-sitter/tree-sitter-json")
          (make "https://github.com/alemuller/tree-sitter-make")
          (markdown "https://github.com/ikatyang/tree-sitter-markdown")
          (python "https://github.com/tree-sitter/tree-sitter-python")
          (toml "https://github.com/tree-sitter/tree-sitter-toml")
          (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
          (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
          (yaml "https://github.com/ikatyang/tree-sitter-yaml")
          (nix "https://github.com/nix-community/tree-sitter-nix")
          (prisma "https://github.com/victorhqc/tree-sitter-prisma")
          (rust "https://github.com/tree-sitter/tree-sitter-rust" )
          (dart "https://github.com/UserNobody14/tree-sitter-dart")))



  (use-package treesit-auto
    :demand t
    :config
    (global-treesit-auto-mode))

  (global-font-lock-mode 1)
  (setq treesit-font-lock-level 4)

  (defun rb/treesit-install-all-grammars ()
    "Install every grammar listed in `treesit-language-source-alist'."
    (interactive)
    (dolist (language (mapcar #'car treesit-language-source-alist))
      (condition-case err
          (treesit-install-language-grammar language)
        (error
         (message "Could not install %s grammar: %s"
                  language (error-message-string err))))))

  (add-to-list 'auto-mode-alist '("\\.nix\\'" . nix-ts-mode))

  ;; Preserve the remaps discovered by the upstream configuration and
  ;; `treesit-auto' instead of replacing the entire table.
  (add-to-list 'major-mode-remap-alist
               '(python-mode . python-ts-mode))

  (provide 'init-treesitter-customizations)
  ;;; init-treesitter-customizations.el ends here

#+end_src

**** Treemacs
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-treemacs.el :mkdirp yes
  ;;; init-treemacs.el --- loads treemacs package -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (use-package treemacs
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "s-0") #'treemacs-select-window))
    :config
    (progn
      (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
            treemacs-deferred-git-apply-delay      0.5
            treemacs-directory-name-transformer    #'identity
            treemacs-display-in-side-window        t
            treemacs-eldoc-display                 t
            treemacs-file-event-delay              5000
            treemacs-file-extension-regex          treemacs-last-period-regex-value
            treemacs-file-follow-delay             0.2
            treemacs-file-name-transformer         #'identity
            treemacs-follow-after-init             t
            treemacs-git-command-pipe              ""
            treemacs-goto-tag-strategy             'refetch-index
            treemacs-indentation                   2
            treemacs-indentation-string            " "
            treemacs-is-never-other-window         nil
            treemacs-max-git-entries               5000
            treemacs-missing-project-action        'ask
            treemacs-no-png-images                 nil
            treemacs-no-delete-other-windows       t
            treemacs-project-follow-cleanup        nil
            treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
            treemacs-position                      'left
            treemacs-recenter-distance             0.1
            treemacs-recenter-after-file-follow    nil
            treemacs-recenter-after-tag-follow     nil
            treemacs-recenter-after-project-jump   'always
            treemacs-recenter-after-project-expand 'on-distance
            treemacs-show-cursor                   nil
            treemacs-show-hidden-files             t
            treemacs-silent-filewatch              nil
            treemacs-silent-refresh                nil
            treemacs-sorting                       'alphabetic-asc
            treemacs-space-between-root-nodes      t
            treemacs-tag-follow-cleanup            t
            treemacs-tag-follow-delay              1.5
            treemacs-user-mode-line-format         nil
            treemacs-width                         40)

      (setf treemacs-read-string-input 'from-minibuffer)
      ;; The default width and height of the icons is 22 pixels. If you are
      ;; using a Hi-DPI display, uncomment this to double the icon size.
      ;;(treemacs-resize-icons 44)

      (treemacs-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode t)
      (pcase (cons (not (null (executable-find "git")))
                   (not (null treemacs-python-executable)))
        (`(t . t)
         (treemacs-git-mode 'deferred))
        (`(t . _)
         (treemacs-git-mode 'simple))))
    :bind
    (:map global-map
          ;; ("s-0"       . treemacs-select-window)
          ("s-0"       . treemacs-add-and-display-current-project-exclusively)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t 0"   . treemacs)
          ("C-x t t"   . treemacs-add-and-display-current-project-exclusively)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

  (use-package treemacs-projectile
    :after (treemacs projectile))

  (use-package treemacs-icons-dired
    :after (treemacs dired)
    :config (treemacs-icons-dired-mode))

  (use-package treemacs-magit
    :after (treemacs magit))

  (use-package treemacs-perspective
    :after (treemacs perspective)
    :config (treemacs-set-scope-type 'Perspectives))

  (use-package treemacs-evil
    :after (treemacs evil))

  (provide 'init-treemacs)
  ;;; init-treemacs.el ends here

#+end_src

**** Use Package
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-use-package.el :mkdirp yes
  ;;; init-use-package.el --- Provides omnisharp -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; Package manager like brew for MacOSX
  ;;; Code:

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package-ensure)
  (setq use-package-always-ensure t)

  (use-package auto-package-update
    :commands (auto-package-update-now)
    :custom
    (auto-package-update-delete-old-versions t)
    (auto-package-update-hide-results t))

  (provide 'init-use-package)
  ;;; init-use-package.el ends here

#+end_src

** Merged Nix additions
These settings came from the former Nix literate configuration. They are kept
in one module so that the personal configuration above remains authoritative
and the additions can be reviewed or disabled independently.

#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-merged-extras.el :mkdirp yes
  ;;; init-merged-extras.el --- Non-conflicting additions from the Nix config -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  (use-package which-key
    :diminish which-key-mode
    :init
    (which-key-mode 1)
    :custom
    (which-key-idle-delay 0.3))

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

  (use-package doom-modeline
    :init
    (doom-modeline-mode 1))

  (use-package doom-themes
    :config
    (setq doom-themes-enable-bold t
          doom-themes-enable-italic t)
    ;; Layering two complete themes produces partially inherited font-lock
    ;; faces. Keep one authoritative theme active.
    (mapc #'disable-theme (copy-sequence custom-enabled-themes))
    (load-theme 'doom-one t)
    (doom-themes-visual-bell-config)
    (doom-themes-org-config))

  (use-package dashboard
    :after projectile
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-startup-banner 'ascii
          dashboard-banner-logo-title "Welcome to your life"
          dashboard-center-content t
          dashboard-items '((projects . 5)
                            (recents . 5))
          dashboard-projects-backend 'projectile
          dashboard-set-file-icons t
          dashboard-set-footer nil
          dashboard-projects-switch-function #'projectile-switch-project-by-name
          initial-buffer-choice (lambda ()
                                  (get-buffer-create "*dashboard*")
                                  (dashboard-refresh-buffer))))

  (use-package visual-fill-column
    :hook (org-mode . rb/org-mode-visual-fill)
    :init
    (defun rb/org-mode-visual-fill ()
      "Center Org text in a comfortably sized column."
      (setq-local visual-fill-column-width 1
                  visual-fill-column-center-text nil)
      (visual-fill-column-mode nil)))

  (use-package org-super-agenda
    :after org-agenda
    :init
    (setq org-agenda-dim-blocked-tasks nil)
    :config
    (setq org-super-agenda-groups
          '((:name "Priority A" :priority "A")
            (:name "Priority B" :priority "B")
            (:name "Priority C" :priority "C")
            (:name "Started" :todo "STARTED")
            (:name "Waiting" :todo "WAITING")
            (:name "Tasks" :todo "TODO")
            (:name "Someday" :todo "SOMEDAY")
            (:name "Projects" :tag "PROJECT")))
    (org-super-agenda-mode 1))

  (use-package org-transclusion
    :after org)

  (defconst rb/org-roam-directory
    (expand-file-name "~/.local/share/org-roam"))
  (make-directory rb/org-roam-directory t)

  (use-package org-roam
    :after org
    :custom
    (org-roam-directory rb/org-roam-directory)
    (org-roam-dailies-directory "daily/")
    (org-roam-completion-everywhere t)
    :bind
    (("C-c r b" . org-roam-buffer-toggle)
     ("C-c r t" . org-roam-dailies-goto-today)
     ("C-c r y" . org-roam-dailies-goto-yesterday)
     ("C-M-n" . org-roam-node-insert)
     ("C-M-f" . org-roam-node-find)
     ("C-`" . org-roam-buffer-toggle))
    :config
    (setq org-roam-capture-templates
          '(("d" "default" plain "%?"
             :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                                "#+title: ${title}\n\n")
             :unnarrowed t))
          org-roam-dailies-capture-templates
          '(("d" "default" entry "* %?"
             :if-new (file+head "%<%Y-%m-%d>.org"
                                "#+title: %<%Y-%m-%d>\n#+filetags: Daily\n\n"))))
    (org-roam-db-autosync-mode 1))

  (use-package org-download
    :after org
    :hook (dired-mode . org-download-enable))

  (use-package writeroom-mode
    :bind ("C-c w" . writeroom-mode))

  (dolist (directory '("~/.local/state/emacs/backup"
                       "~/.local/state/emacs/lock-files"))
    (make-directory (expand-file-name directory) t))

  (setq backup-directory-alist '((".*" . "~/.local/state/emacs/backup"))
        backup-by-copying t
        version-control t
        delete-old-versions t
        auto-save-file-name-transforms '((".*" "~/.local/state/emacs/" t))
        lock-file-name-transforms '((".*" "~/.local/state/emacs/lock-files/" t)))

  (provide 'init-merged-extras)
  ;;; init-merged-extras.el ends here
#+end_src

**** Vertico
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-minibuffer-customizations.el :mkdirp yes
  ;;; init-minibuffer-customizations.el --- Provides omnisharp -*- lexical-binding: t -*-
  ;;; Commentary:
  ;; MiniBuffer customizations
  ;;; Code:

  ;; Configure directory extension.
  (use-package vertico-directory
    :after vertico
    :ensure nil
    ;; More convenient directory navigation commands
    :bind (:map vertico-map
                ("RET" . vertico-directory-enter)
                ("DEL" . vertico-directory-delete-word)
                ("M-DEL" . vertico-directory-delete-char))
    ;; Tidy shadowed file names
    :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))

  ;; Enable vertico-multiform
  ;; (vertico-multiform-mode)

  ;; Configure the display per command.
  ;; Use a buffer with indices for imenu
  ;; and a flat (Ido-like) menu for M-x.
  ;; (setq vertico-multiform-commands
  ;; '((consult-imenu buffer indexed)))

  ;; Configure the display per completion category.
  ;; Use the grid display for files and a buffer
  ;; for the consult-grep commands.
  ;; (setq vertico-multiform-categories
  ;; '((consult-grep buffer)))

  (provide 'init-minibuffer-customizations)
  ;;; init-minibuffer-customizations.el ends here

#+end_src

**** Web Dev
#+begin_src emacs-lisp :tangle ~/.emacs.d/custom/init-webdev.el :mkdirp yes
  ;;; init-webbed.el --- loads treemacs package -*- lexical-binding: t -*-
  ;;; Commentary:
  ;;; Code:

  ;;------------------------------------------------------------------------------
  ;; Set up web-mode
  ;;------------------------------------------------------------------------------
  ;; (use-package web-mode
  ;;   :config
  ;;   (setq web-mode-attr-indent-offset 'standard-indent)
  ;;   (setq web-mode-enable-auto-closing t)
  ;;   (setq web-mode-enable-current-column-highlight t)
  ;;   (setq web-mode-enable-current-element-highlight t))

  ;; 
  (when (maybe-require-package 'add-node-modules-path)
    (dolist (mode '(ts-mode tsx-ts-mode js-mode js2-mode))
      (add-hook (intern (format "%s-hook" mode)) #'add-node-modules-path)))

  ;;------------------------------------------------------------------------------
  ;; Auto format language servers
  ;;------------------------------------------------------------------------------
  (use-package apheleia)

  (dolist (mode '(bash-ts-mode-hook
                  c-mode-hook
                  closure-ts-mode-hook
                  dockerfile-mode-hook
                  php-mode-hook
                  python-mode-hook
                  python-ts-mode-hook
                  prisma-ts-mode-hook
                  ruby-mode-hook
                  ruby-ts-mode-hook
                  rust-mode-hook
                  go-mode-hook
                  go-ts-mode-hook
                  rust-ts-mode-hook
                  terraform-mode-hook
                  yaml-mode-hook
                  c++-mode-hook))
    (add-hook mode 'apheleia-mode))

  (use-package prettier
    :hook (after-init . global-prettier-mode)
    (tsx-ts-mode . prettier-mode)
    (js-jsx-mode . prettier-mode)
    (js-jsx-mode . prettier-mode)
    (json-mode . prettier-mode)
    (json-ts-mode . prettier-mode)
    (typescript-ts-mode . prettier-mode))

  (add-hook 'after-init-hook #'global-prettier-mode)

  ;;------------------------------------------------------------------------------
  ;; Add these files to web-mode list
  ;;------------------------------------------------------------------------------
  (defun rb/web-mode ()
    "Add some file to `auto-mode-alist'."
    (mapc
     (lambda (x)
       (add-to-list 'auto-mode-alist (cons x 'tsx-ts-mode)))
     '("\\.jsx\\'" "\\.tsx\\'")))

  (rb/web-mode)

  ;; ------------------------------------------------------------------------------
  ;; Run emmet-mode in web-mode
  ;;------------------------------------------------------------------------------
  (use-package emmet-mode
    :init
    (bind-key "C-<return>" 'emmet-expand-line)
    (bind-key "s-8" 'emmet-prev-edit-point)
    (bind-key "s-9" 'emmet-next-edit-point)
    (add-hook 'web-mode-hook  'emmet-mode)
    (add-hook 'sgml-mode-hook 'emmet-mode)
    (add-hook 'css-mode-hook  'emmet-mode))


  (unless (package-installed-p 'indium)
    (package-install 'indium))

  (provide 'init-webdev)
  ;;; init-webdev.el ends here

#+end_src
